/* Generated By:JavaCC: Do not edit this line. AssociationParserConstants.java */
package org.mxupdate.update.user;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface AssociationParserConstants_mxJPO {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DESCRIPTION = 5;
  /** RegularExpression Id. */
  int HIDDEN_TRUE = 6;
  /** RegularExpression Id. */
  int HIDDEN_FALSE = 7;
  /** RegularExpression Id. */
  int DEFINITION = 8;
  /** RegularExpression Id. */
  int STRING = 9;
  /** RegularExpression Id. */
  int SINGLE = 10;
  /** RegularExpression Id. */
  int MULTILINESTRING = 11;
  /** RegularExpression Id. */
  int MULTILINESINGLE = 12;
  /** RegularExpression Id. */
  int PROPERTY = 13;
  /** RegularExpression Id. */
  int PROPERTYTO = 14;
  /** RegularExpression Id. */
  int PROPERTYVAL = 15;
  /** RegularExpression Id. */
  int ADMINTYPE_STRING = 16;
  /** RegularExpression Id. */
  int ADMINTYPE_SINGLE = 17;

  /** Lexical state. */
  int ADMINREF_EXPECTED = 0;
  /** Lexical state. */
  int MULTILINESTRING_EXPECTED = 1;
  /** Lexical state. */
  int STRING_EXPECTED = 2;
  /** Lexical state. */
  int DEFAULT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 4>",
    "\"description\"",
    "\"hidden\"",
    "\"!hidden\"",
    "\"definition\"",
    "<STRING>",
    "<SINGLE>",
    "<MULTILINESTRING>",
    "<MULTILINESINGLE>",
    "\"property\"",
    "\"to\"",
    "\"value\"",
    "<ADMINTYPE_STRING>",
    "<ADMINTYPE_SINGLE>",
  };

}
