/* Generated By:JavaCC: Do not edit this line. RoleParserConstants.java */
package org.mxupdate.update.user;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface RoleParserConstants_mxJPO {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SYMBOLICNAME = 5;
  /** RegularExpression Id. */
  int DESCRIPTION = 6;
  /** RegularExpression Id. */
  int HIDDEN_TRUE = 7;
  /** RegularExpression Id. */
  int HIDDEN_FALSE = 8;
  /** RegularExpression Id. */
  int PARENT = 9;
  /** RegularExpression Id. */
  int SITE = 10;
  /** RegularExpression Id. */
  int STRING = 11;
  /** RegularExpression Id. */
  int SINGLE = 12;
  /** RegularExpression Id. */
  int MULTILINESTRING = 13;
  /** RegularExpression Id. */
  int MULTILINESINGLE = 14;
  /** RegularExpression Id. */
  int KIND = 15;
  /** RegularExpression Id. */
  int ORGANIZATION = 16;
  /** RegularExpression Id. */
  int PROJECT = 17;
  /** RegularExpression Id. */
  int ROLE = 18;
  /** RegularExpression Id. */
  int PROPERTY = 19;
  /** RegularExpression Id. */
  int PROPERTYTO = 20;
  /** RegularExpression Id. */
  int PROPERTYVAL = 21;
  /** RegularExpression Id. */
  int ADMINTYPE_STRING = 22;
  /** RegularExpression Id. */
  int ADMINTYPE_SINGLE = 23;

  /** Lexical state. */
  int ADMINREF_EXPECTED = 0;
  /** Lexical state. */
  int KIND_EXPECTED = 1;
  /** Lexical state. */
  int MULTILINESTRING_EXPECTED = 2;
  /** Lexical state. */
  int STRING_EXPECTED = 3;
  /** Lexical state. */
  int DEFAULT = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 4>",
    "\"symbolicname\"",
    "\"description\"",
    "\"hidden\"",
    "\"!hidden\"",
    "\"parent\"",
    "\"site\"",
    "<STRING>",
    "<SINGLE>",
    "<MULTILINESTRING>",
    "<MULTILINESINGLE>",
    "\"kind\"",
    "\"organization\"",
    "\"project\"",
    "\"role\"",
    "\"property\"",
    "\"to\"",
    "\"value\"",
    "<ADMINTYPE_STRING>",
    "<ADMINTYPE_SINGLE>",
  };

}
