/* Generated By:JavaCC: Do not edit this line. RelationshipDefParserConstants.java */
package org.mxupdate.update.datamodel.relationship;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RelationshipDefParserConstants_mxJPO {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DESCRIPTION = 5;
  /** RegularExpression Id. */
  int ABSTRACT_TRUE = 6;
  /** RegularExpression Id. */
  int ABSTRACT_FALSE = 7;
  /** RegularExpression Id. */
  int DERIVED = 8;
  /** RegularExpression Id. */
  int HIDDEN_TRUE = 9;
  /** RegularExpression Id. */
  int HIDDEN_FALSE = 10;
  /** RegularExpression Id. */
  int PREVENTDUPLICATES_TRUE = 11;
  /** RegularExpression Id. */
  int PREVENTDUPLICATES_FALSE = 12;
  /** RegularExpression Id. */
  int ATTRIBUTE = 13;
  /** RegularExpression Id. */
  int RULE = 14;
  /** RegularExpression Id. */
  int STRING = 19;
  /** RegularExpression Id. */
  int SINGLE = 20;
  /** RegularExpression Id. */
  int APOSTROPHE = 21;
  /** RegularExpression Id. */
  int CHAR = 22;
  /** RegularExpression Id. */
  int KIND = 23;
  /** RegularExpression Id. */
  int BASIC = 28;
  /** RegularExpression Id. */
  int COMPOSITIONAL = 29;
  /** RegularExpression Id. */
  int TRIGGER = 30;
  /** RegularExpression Id. */
  int INPUT = 31;
  /** RegularExpression Id. */
  int TRIGEVENT = 36;
  /** RegularExpression Id. */
  int ACTION = 41;
  /** RegularExpression Id. */
  int CHECK = 42;
  /** RegularExpression Id. */
  int OVERRIDE = 43;
  /** RegularExpression Id. */
  int START_FROM = 44;
  /** RegularExpression Id. */
  int START_TO = 45;
  /** RegularExpression Id. */
  int FROMTO_PROPAGATEMODIFY_TRUE = 50;
  /** RegularExpression Id. */
  int FROMTO_PROPAGATEMODIFY_FALSE = 51;
  /** RegularExpression Id. */
  int FROMTO_PROPAGATECONNECTION_TRUE = 52;
  /** RegularExpression Id. */
  int FROMTO_PROPAGATECONNECTION_FALSE = 53;
  /** RegularExpression Id. */
  int FROMTO_MEANING = 54;
  /** RegularExpression Id. */
  int FROMTO_REVISION_NONE = 55;
  /** RegularExpression Id. */
  int FROMTO_REVISION_FLOAT = 56;
  /** RegularExpression Id. */
  int FROMTO_REVISION_REPLICATE = 57;
  /** RegularExpression Id. */
  int FROMTO_CLONE_NONE = 58;
  /** RegularExpression Id. */
  int FROMTO_CLONE_FLOAT = 59;
  /** RegularExpression Id. */
  int FROMTO_CLONE_REPLICATE = 60;
  /** RegularExpression Id. */
  int FROMTO_CARDINALITY_ONE = 61;
  /** RegularExpression Id. */
  int FROMTO_CARDINALITY_MANY = 62;
  /** RegularExpression Id. */
  int FROMTO_TYPE_ALL = 63;
  /** RegularExpression Id. */
  int FROMTO_TYPE = 64;
  /** RegularExpression Id. */
  int FROMTO_RELATIONSHIP_ALL = 65;
  /** RegularExpression Id. */
  int FROMTO_RELATIONSHIP = 66;
  /** RegularExpression Id. */
  int FROMTO_END = 67;
  /** RegularExpression Id. */
  int FROMTO_STRING = 72;
  /** RegularExpression Id. */
  int FROMTO_SINGLE = 73;
  /** RegularExpression Id. */
  int FROMTO_APOSTROPHE = 74;
  /** RegularExpression Id. */
  int FROMTO_CHAR = 75;
  /** RegularExpression Id. */
  int PROPERTY = 76;
  /** RegularExpression Id. */
  int PROPERTYTO = 77;
  /** RegularExpression Id. */
  int PROPERTYVAL = 78;
  /** RegularExpression Id. */
  int ADMINTYPE_STRING = 83;
  /** RegularExpression Id. */
  int ADMINTYPE_SINGLE = 84;
  /** RegularExpression Id. */
  int ADMINTYPE_APOSTROPHE = 85;
  /** RegularExpression Id. */
  int ADMINTYPE_CHAR = 86;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_EXPECTED = 1;
  /** Lexical state. */
  int KIND_EXPECTED = 2;
  /** Lexical state. */
  int TRIGEVENT_EXPECTED = 3;
  /** Lexical state. */
  int TRIGKIND_EXPECTED = 4;
  /** Lexical state. */
  int FROMTO_EXPECTED = 5;
  /** Lexical state. */
  int FROMTO_STRING_EXPECTED = 6;
  /** Lexical state. */
  int ADMINREF_EXPECTED = 7;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"description\"",
    "\"abstract\"",
    "\"!abstract\"",
    "\"derived\"",
    "\"hidden\"",
    "\"!hidden\"",
    "\"preventduplicates\"",
    "\"!preventduplicates\"",
    "\"attribute\"",
    "\"rule\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<STRING>",
    "<SINGLE>",
    "\"\\\"\"",
    "<CHAR>",
    "\"kind\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"basic\"",
    "\"compositional\"",
    "\"trigger\"",
    "\"input\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<TRIGEVENT>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"action\"",
    "\"check\"",
    "\"override\"",
    "<START_FROM>",
    "<START_TO>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"propagatemodify\"",
    "\"!propagatemodify\"",
    "\"propagateconnection\"",
    "\"!propagateconnection\"",
    "\"meaning\"",
    "<FROMTO_REVISION_NONE>",
    "<FROMTO_REVISION_FLOAT>",
    "<FROMTO_REVISION_REPLICATE>",
    "<FROMTO_CLONE_NONE>",
    "<FROMTO_CLONE_FLOAT>",
    "<FROMTO_CLONE_REPLICATE>",
    "<FROMTO_CARDINALITY_ONE>",
    "<FROMTO_CARDINALITY_MANY>",
    "<FROMTO_TYPE_ALL>",
    "\"type\"",
    "<FROMTO_RELATIONSHIP_ALL>",
    "\"relationship\"",
    "\"}\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<FROMTO_STRING>",
    "<FROMTO_SINGLE>",
    "\"\\\"\"",
    "<FROMTO_CHAR>",
    "\"property\"",
    "\"to\"",
    "\"value\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<ADMINTYPE_STRING>",
    "<ADMINTYPE_SINGLE>",
    "\"\\\"\"",
    "<ADMINTYPE_CHAR>",
  };

}
