/*
 *  This file is part of MxUpdate <http://www.mxupdate.org>.
 *
 *  MxUpdate is a deployment tool for a PLM platform to handle
 *  administration objects as single update files (configuration item).
 *
 *  Copyright (C) 2008-2016 The MxUpdate Team - All Rights Reserved
 *
 *  You may use, distribute and modify MxUpdate under the terms of the
 *  MxUpdate license. You should have received a copy of the MxUpdate
 *  license with this file. If not, please write to <info@mxupdate.org>,
 *  or visit <www.mxupdate.org>.
 *
 */

package org.mxupdate.test.test.update.datamodel;

import org.mxupdate.test.test.update.AbstractParserTest;
import org.mxupdate.update.datamodel.Policy_mxJPO;
import org.mxupdate.update.util.ParameterCache_mxJPO;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

/**
 * Tests the {@link Policy_mxJPO policy CI} parser.
 *
 * @author The MxUpdate Team
 */
@Test()
public class PolicyCI_1ParserTest
    extends AbstractParserTest<Policy_mxJPO>
{
    @Override()
    @DataProvider(name = "data")
    public Object[][] getData()
    {
        final String simple = "description \"\" hidden type {} format {} defaultformat \"\" sequence \"\" store \"\" ";
        final String state  = "registeredName \"\" !enforcereserveaccess !majorrevision !minorrevision !version !promote !checkouthistory !published ";

        return new Object[][]{
                {"1) simple policy",
                        "",
                        simple},
                // description
                {"2a) description",
                        "",
                        "description \"abc def\" !hidden type {} format {} defaultformat \"\" sequence \"\" store \"\""},
                {"2b) description not defined",
                        "description \"\" !hidden type {} format {} defaultformat \"\" sequence \"\" store \"\"",
                        "                 !hidden type {} format {} defaultformat \"\" sequence \"\" store \"\""},
                {"2c) multi-line description",
                        "",
                        "description \"abc\ndef\" !hidden type {} format {} defaultformat \"\" sequence \"\" store \"\""},
                // hidden flag
                {"3a) simple not hidden policy",
                        "",
                        "description \"\" !hidden type {} format {} defaultformat \"\" sequence \"\" store \"\""},
                {"3b) not hidden policy defined as value w/o apostrophe",
                        "description \"\" !hidden type {} format {} defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" hidden false type {} format {} defaultformat \"\" sequence \"\" store \"\""},
                {"3c) not hidden policy defined as value with apostrophe",
                        "description \"\" !hidden type {} format {} defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" hidden \"FAlse\" type {} format {} defaultformat \"\" sequence \"\" store \"\""},
                {"3d) hidden policy",
                        "",
                        "description \"\" hidden type {} format {} defaultformat \"\" sequence \"\" store \"\""},
                {"3e) hidden hidden defined as value w/o apostrophe",
                        "description \"\" hidden type {} format {} defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" hidden TRUE type {} format {} defaultformat \"\" sequence \"\" store \"\""},
                {"3f) hidden policy defined as value with apostrophe",
                        "description \"\" hidden type {} format {} defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" hidden \"True\" type {} format {} defaultformat \"\" sequence \"\" store \"\""},
                // enforce flag
                {"4a) not enforce policy",
                        "description \"\" !hidden type {} format {} defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" !hidden type {} format {} defaultformat \"\" !enforce sequence \"\" store \"\""},
                {"4b) not enforce policy defined as value w/o apostrophe",
                        "description \"\" !hidden type {} format {} defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" !hidden type {} format {} defaultformat \"\" enforce false sequence \"\" store \"\""},
                {"4c) not enforce policy defined as value with apostrophe",
                        "description \"\" !hidden type {} format {} defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" !hidden type {} format {} defaultformat \"\" enforce \"FAlse\" sequence \"\" store \"\""},
                {"4d) enforce policy",
                        "",
                        "description \"\" !hidden type {} format {} defaultformat \"\" enforce sequence \"\" store \"\""},
                {"4e) enforce policy defined as value w/o apostrophe",
                        "description \"\" !hidden type {} format {} defaultformat \"\" enforce sequence \"\" store \"\"",
                        "description \"\" !hidden type {} format {} defaultformat \"\" enforce TRUE sequence \"\" store \"\""},
                {"4f) enforce policy defined as value with apostrophe",
                        "description \"\" !hidden type {} format {} defaultformat \"\" enforce sequence \"\" store \"\"",
                        "description \"\" !hidden type {} format {} defaultformat \"\" enforce \"True\" sequence \"\" store \"\""},
                // special characters
                {"5a) policy with description special characters",
                        "",
                        "description \"{}\\\"\" hidden type {} format {} defaultformat \"\" sequence \"\" store \"\""},
                {"5b) policy with type special characters",
                        "",
                        "description \"\" hidden type {\"{}\\\"\"} format {} defaultformat \"\" sequence \"\" store \"\""},
                {"5c) policy with format special characters",
                        "",
                        "description \"\" hidden type {} format {\"{}\\\"\"} defaultformat \"\" sequence \"\" store \"\""},
                {"5d) policy with defaultformat special characters",
                        "",
                        "description \"\" hidden type {} format {} defaultformat \"{}\\\"\" sequence \"\" store \"\""},
                {"5e) policy with sequence special characters",
                        "",
                        "description \"\" hidden type {} format {} defaultformat \"\" sequence \"{}\\\"\" store \"\""},
                {"5f) policy with store special characters",
                        "",
                        "description \"\" hidden type {} format {} defaultformat \"\" sequence \"\" store \"{}\\\"\""},
                {"5g) policy with delimeter / minor special characters",
                        "",
                        "description \"\" hidden type {} format {} defaultformat \"\" delimiter \".\" minorsequence \"{}\\\"\" majorsequence \"{}\\\"\" store \"\""},
                // policy property
                {"6a) policy with property special characters",
                        "",
                        simple + "property \"{}\\\"\""},
                {"6b) policy with property and value special characters",
                        "",
                        simple + "property \"{}\\\"\" value \"{}\\\"\""},
                {"6c) policy with property link special characters",
                        "",
                        simple + "property \"{}\\\"\" to type \"{}\\\"\""},
                {"6d) policy with property link and value special characters",
                        "",
                        simple + "property \"{}\\\"\" to type \"{}\\\"\" value \"{}\\\"\""},
                // policy state with special characters
                {"7a) policy with state symbolic name special characters",
                        "",
                        simple + "state \"{}\\\"\" { registeredName \"{}\\\"\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"7b) policy with state action",
                        "",
                        simple + "state \"A\" { registeredName \"A\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published action \"AAA\" input \"\" }"},
                {"7c) policy with empty state action",
                        simple + "state \"A\" { registeredName \"A\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"A\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published action \"\" input \"\" }"},
                {"7d) policy with state action input",
                        "",
                        simple + "state \"A\" { registeredName \"A\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published action \"\" input \"AAA\" }"},
                {"7e) policy with state check",
                        "",
                        simple + "state \"A\" { registeredName \"A\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published check \"AAA\" input \"\" }"},
                {"7f) policy with empty state check",
                        simple + "state \"A\" { registeredName \"A\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"A\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published check \"\" input \"\" }"},
                {"7g) policy with state check input",
                        "",
                        simple + "state \"A\" { registeredName \"A\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published check \"\" input \"AAA\" }"},
                // policy state property
                {"8a) policy with state property special characters",
                        "",
                        simple + "state \"A\" { registeredName \"\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published property \"{}\\\"\" }"},
                {"8b) policy with state property and value special characters",
                        "",
                        simple + "state \"A\" { registeredName \"\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published property \"{}\\\"\" value \"{}\\\"\" }"},
                {"8c) policy with state property link special characters",
                        "",
                        simple + "state \"A\" { registeredName \"\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published property \"{}\\\"\" to type \"{}\\\"\" }"},
                {"8d) policy with state property link and value special characters",
                        "",
                        simple + "state \"A\" { registeredName \"\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published property \"{}\\\"\" to type \"{}\\\"\" value \"{}\\\"\" }"},
                // policy state with enforce flag
                {"9a) policy state not enforcereserveaccess",
                        "",
                        simple + "state \"A\" { registeredName \"\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"9b) policy state not enforcereserveaccess defined as not",
                        simple + "state \"A\" { registeredName \"\"   !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" notenforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"9c) policy state not enforcereserveaccess defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess false majorrevision minorrevision version promote checkouthistory published }"},
                {"9d) policy state not enforcereserveaccess defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess \"FAlse\" majorrevision minorrevision version promote checkouthistory published }"},
                {"9e) policy state enforcereserveaccess",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"9f) policy state enforcereserveaccess defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess TRUE majorrevision minorrevision version promote checkouthistory published }"},
                {"9g) policy state enforcereserveaccess defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess \"True\" majorrevision minorrevision version promote checkouthistory published }"},
                // policy state with majorrevision flag
                {"10a) policy state not majorrevision",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess !majorrevision minorrevision version promote checkouthistory published }"},
                {"10b) policy state not majorrevision defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess !majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision false minorrevision version promote checkouthistory published }"},
                {"10c) policy state not majorrevision defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess !majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision \"FAlse\" minorrevision version promote checkouthistory published }"},
                {"10d) policy state majorrevision",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"10e) policy state majorrevision defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision TRUE minorrevision version promote checkouthistory published }"},
                {"10f) policy state majorrevision defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision \"True\" minorrevision version promote checkouthistory published }"},
                // policy state with minorrevision flag
                {"11a) policy state not minorrevision",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision !minorrevision version promote checkouthistory published }"},
                {"11b) policy state not minorrevision defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision !minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision false version promote checkouthistory published }"},
                {"11c) policy state not minorrevision defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision !minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision \"FAlse\" version promote checkouthistory published }"},
                {"11d) policy state minorrevision",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"11e) policy state minorrevision defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision TRUE version promote checkouthistory published }"},
                {"11f) policy state minorrevision defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision \"True\" version promote checkouthistory published }"},
                // policy state with revision flag
                {"12a) policy state not revision",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision !minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision !revision version promote checkouthistory published }"},
                {"12b) policy state not minorrevision defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision !minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision revision false version promote checkouthistory published }"},
                {"12c) policy state not minorrevision defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision !minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision revision \"FAlse\" version promote checkouthistory published }"},
                {"12d) policy state minorrevision",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision revision version promote checkouthistory published }"},
                {"12e) policy state minorrevision defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision revision TRUE version promote checkouthistory published }"},
                {"12f) policy state minorrevision defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision revision \"True\" version promote checkouthistory published }"},
                // policy state with version flag
                {"13a) policy state not version",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision !version promote checkouthistory published }"},
                {"13b) policy state not version defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision !version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version false promote checkouthistory published }"},
                {"13c) policy state not version defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision !version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version \"FAlse\" promote checkouthistory published }"},
                {"13d) policy state version",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"13e) policy state version defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version TRUE promote checkouthistory published }"},
                {"13f) policy state version defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version \"True\" promote checkouthistory published }"},
                // policy state with promote flag
                {"14a) policy state not promote",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version !promote checkouthistory published }"},
                {"14b) policy state not promote defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version !promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote false checkouthistory published }"},
                {"14c) policy state not promote defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version !promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote \"FAlse\" checkouthistory published }"},
                {"14d) policy state promote",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"14e) policy state promote defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote TRUE checkouthistory published }"},
                {"14f) policy state promote defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote \"True\" checkouthistory published }"},
                // policy state with checkouthistory flag
                {"15a) policy state not checkouthistory",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote !checkouthistory published }"},
                {"15b) policy state not checkouthistory defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote !checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory false published }"},
                {"15c) policy state not checkouthistory defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote !checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory \"FAlse\" published }"},
                {"15d) policy state checkouthistory",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"15e) policy state checkouthistory defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory TRUE published }"},
                {"15f) policy state checkouthistory defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory \"True\" published }"},
                // policy state with published flag
                {"16a) policy state not published",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory !published }"},
                {"16b) policy state not published defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory !published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published false }"},
                {"16c) policy state not published defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory !published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published \"FAlse\" }"},
                {"16d) policy state published",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"16e) policy state published defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published TRUE }"},
                {"16f) policy state published defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published \"True\" }"},

                // all state owner
                {"20a) all state owner", "", simple + "allstate {              owner             {read} }"},
                {"20b) all state owner", "", simple + "allstate {        login owner             {read} }"},
                {"20c) all state owner", "", simple + "allstate { revoke       owner             {read} }"},
                {"20d) all state owner", "", simple + "allstate { revoke login owner             {read} }"},
                {"20e) all state owner", "", simple + "allstate {              owner key \"key\" {read} }"},
                {"20f) all state owner", "", simple + "allstate {        login owner key \"key\" {read} }"},
                {"20g) all state owner", "", simple + "allstate { revoke       owner key \"key\" {read} }"},
                {"20h) all state owner", "", simple + "allstate { revoke login owner key \"key\" {read} }"},
                // all state public
                {"21a) all state public", "", simple + "allstate {              public             {read} }"},
                {"21b) all state public", "", simple + "allstate {        login public             {read} }"},
                {"21c) all state public", "", simple + "allstate { revoke       public             {read} }"},
                {"21d) all state public", "", simple + "allstate { revoke login public             {read} }"},
                {"21e) all state public", "", simple + "allstate {              public key \"key\" {read} }"},
                {"21f) all state public", "", simple + "allstate {        login public key \"key\" {read} }"},
                {"21g) all state public", "", simple + "allstate { revoke       public key \"key\" {read} }"},
                {"21h) all state public", "", simple + "allstate { revoke login public key \"key\" {read} }"},
                // allstate state user
                {"22a) all state user", "", simple + "allstate {              user \"createor\"             {read} }"},
                {"22b) all state user", "", simple + "allstate {        login user \"createor\"             {read} }"},
                {"22c) all state user", "", simple + "allstate { revoke       user \"createor\"             {read} }"},
                {"22d) all state user", "", simple + "allstate { revoke login user \"createor\"             {read} }"},
                {"22e) all state user", "", simple + "allstate {              user \"createor\" key \"key\" {read} }"},
                {"22f) all state user", "", simple + "allstate {        login user \"createor\" key \"key\" {read} }"},
                {"22g) all state user", "", simple + "allstate { revoke       user \"createor\" key \"key\" {read} }"},
                {"22h) all state user", "", simple + "allstate { revoke login user \"createor\" key \"key\" {read} }"},

                // single state owner
                {"30a) single state owner", "", simple + "state \"A\" { " + state + "              owner             {read} }"},
                {"30b) single state owner", "", simple + "state \"A\" { " + state + "        login owner             {read} }"},
                {"30c) single state owner", "", simple + "state \"A\" { " + state + " revoke       owner             {read} }"},
                {"30d) single state owner", "", simple + "state \"A\" { " + state + " revoke login owner             {read} }"},
                {"30e) single state owner", "", simple + "state \"A\" { " + state + "              owner key \"key\" {read} }"},
                {"30f) single state owner", "", simple + "state \"A\" { " + state + "        login owner key \"key\" {read} }"},
                {"30g) single state owner", "", simple + "state \"A\" { " + state + " revoke       owner key \"key\" {read} }"},
                {"30h) single state owner", "", simple + "state \"A\" { " + state + " revoke login owner key \"key\" {read} }"},
                // single state public
                {"31a) single state public", "", simple + "state \"A\" { " + state + "              public             {read} }"},
                {"31b) single state public", "", simple + "state \"A\" { " + state + "        login public             {read} }"},
                {"31c) single state public", "", simple + "state \"A\" { " + state + " revoke       public             {read} }"},
                {"31d) single state public", "", simple + "state \"A\" { " + state + " revoke login public             {read} }"},
                {"31e) single state public", "", simple + "state \"A\" { " + state + "              public key \"key\" {read} }"},
                {"31f) single state public", "", simple + "state \"A\" { " + state + "        login public key \"key\" {read} }"},
                {"31g) single state public", "", simple + "state \"A\" { " + state + " revoke       public key \"key\" {read} }"},
                {"31h) single state public", "", simple + "state \"A\" { " + state + " revoke login public key \"key\" {read} }"},
                // single state user
                {"32a) single state user", "", simple + "state \"A\" { " + state + "              user \"createor\"             {read} }"},
                {"32b) single state user", "", simple + "state \"A\" { " + state + "        login user \"createor\"             {read} }"},
                {"32c) single state user", "", simple + "state \"A\" { " + state + " revoke       user \"createor\"             {read} }"},
                {"32d) single state user", "", simple + "state \"A\" { " + state + " revoke login user \"createor\"             {read} }"},
                {"32e) single state user", "", simple + "state \"A\" { " + state + "              user \"createor\" key \"key\" {read} }"},
                {"32f) single state user", "", simple + "state \"A\" { " + state + "        login user \"createor\" key \"key\" {read} }"},
                {"32g) single state user", "", simple + "state \"A\" { " + state + " revoke       user \"createor\" key \"key\" {read} }"},
                {"32h) single state user", "", simple + "state \"A\" { " + state + " revoke login user \"createor\" key \"key\" {read} }"},

                // state route
                {"40a) state with route",                "", simple + "state \"A\" { " + state + " route {\"abc\"} \"\"     }"},
                {"40b) state with route & message",      "", simple + "state \"A\" { " + state + " route {\"abc\"} \"abc\"  }"},
                {"40c) state with multiple route users (to test sorting)",
                        simple + "state \"A\" { " + state + " route {\"abc\" \"def\"} \"\" }",
                        simple + "state \"A\" { " + state + " route {\"def\" \"abc\"} \"\" }"},
                {"40d) state with empty route user",
                        simple + "state \"A\" { " + state + "               }",
                        simple + "state \"A\" { " + state + " route {} \"\" }"},

                // state trigger
                {"50a) state with check trigger",               "", simple + "state \"A\" { " + state + " trigger modify check    \"Prog\" input \"\" }"},
                {"50b) state with check trigger & input",       "", simple + "state \"A\" { " + state + " trigger modify check    \"Prog\" input \"abc\" }"},
                {"50c) state with check trigger & empty input",
                        simple + "state \"A\" { " + state + " trigger modify check    \"Prog\" input \"\" }",
                        simple + "state \"A\" { " + state + " trigger modify check    \"Prog\"            }"},
                {"51a) state with override trigger",         "", simple + "state \"A\" { " + state + " trigger modify override \"Prog\" input \"\" }"},
                {"51b) state with override trigger & input", "", simple + "state \"A\" { " + state + " trigger modify override \"Prog\" input \"abc\" }"},
                {"51c) state with check trigger & empty input",
                        simple + "state \"A\" { " + state + " trigger modify override    \"Prog\" input \"\" }",
                        simple + "state \"A\" { " + state + " trigger modify override    \"Prog\"            }"},

                {"52a) state with action trigger",           "", simple + "state \"A\" { " + state + " trigger modify action   \"Prog\" input \"\" }"},
                {"52b) state with action trigger & input",   "", simple + "state \"A\" { " + state + " trigger modify action   \"Prog\" input \"abc\" }"},
                {"52c) state with check trigger & no input",
                        simple + "state \"A\" { " + state + " trigger modify action    \"Prog\" input \"\" }",
                        simple + "state \"A\" { " + state + " trigger modify action    \"Prog\"             }"},

                // state signature (branch)
                {"60a) state with signature",         "", simple + "state \"A\" { " + state + " signature \"A\" { branch \"\"    approve {}        ignore {}        reject {}        filter \"\"    } }"},
                {"60b) state with signature branch",  "", simple + "state \"A\" { " + state + " signature \"A\" { branch \"abc\" approve {}        ignore {}        reject {}        filter \"\"    } }"},
                {"60c) state with signature approve", "", simple + "state \"A\" { " + state + " signature \"A\" { branch \"\"    approve {\"abc\"} ignore {}        reject {}        filter \"\"    } }"},
                {"60d) state with signature ignore",  "", simple + "state \"A\" { " + state + " signature \"A\" { branch \"\"    approve {}        ignore {\"abc\"} reject {}        filter \"\"    } }"},
                {"60e) state with signature reject",  "", simple + "state \"A\" { " + state + " signature \"A\" { branch \"\"    approve {}        ignore {}        reject {\"abc\"} filter \"\"    } }"},
                {"60f) state with signature filter",  "", simple + "state \"A\" { " + state + " signature \"A\" { branch \"\"    approve {}        ignore {}        reject {}        filter \"abc\" } }"},
                {"60g) state with empty signature value (to check default values)",
                        simple + "state \"A\" { " + state + " signature \"A\" { branch \"\" approve {} ignore {} reject {} filter \"\" } }",
                        simple + "state \"A\" { " + state + " signature \"A\" { } }"},
        };
    }

    @Override()
    protected Policy_mxJPO createNewData(final ParameterCache_mxJPO _paramCache,
                                         final String _name)
    {
        return new Policy_mxJPO(_paramCache.getMapping().getTypeDef(CI.DM_POLICY.updateType), _name);
    }
}
