/*
 *  This file is part of MxUpdate <http://www.mxupdate.org>.
 *
 *  MxUpdate is a deployment tool for a PLM platform to handle
 *  administration objects as single update files (configuration item).
 *
 *  Copyright (C) 2008-2016 The MxUpdate Team - All Rights Reserved
 *
 *  You may use, distribute and modify MxUpdate under the terms of the
 *  MxUpdate license. You should have received a copy of the MxUpdate
 *  license with this file. If not, please write to <info@mxupdate.org>,
 *  or visit <www.mxupdate.org>.
 *
 */

package org.mxupdate.test.test.update.datamodel;

import org.mxupdate.test.test.update.AbstractParserTest;
import org.mxupdate.update.datamodel.Policy_mxJPO;
import org.mxupdate.update.util.ParameterCache_mxJPO;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

/**
 * Tests the {@link Policy_mxJPO policy CI} parser.
 *
 * @author The MxUpdate Team
 */
@Test()
public class PolicyCI_1ParserTest
    extends AbstractParserTest<Policy_mxJPO>
{
    @Override()
    @DataProvider(name = "data")
    public Object[][] getData()
    {
        final String simple = "description \"\" hidden defaultformat \"\" sequence \"\" store \"\" ";
        final String state  = "registeredName \"\" !enforcereserveaccess !majorrevision !minorrevision !version !promote !checkouthistory !published ";

        return new Object[][]{
                {"1) simple policy",
                        "",
                        simple},
                // description
                {"2a) description",
                        "",
                        "description \"abc def\" !hidden defaultformat \"\" sequence \"\" store \"\""},
                {"2b) description not defined",
                        "description \"\" !hidden defaultformat \"\" sequence \"\" store \"\"",
                        "                 !hidden defaultformat \"\" sequence \"\" store \"\""},
                {"2c) multi-line description",
                        "",
                        "description \"abc\ndef\" !hidden defaultformat \"\" sequence \"\" store \"\""},
                // hidden flag
                {"3a) simple not hidden policy",
                        "",
                        "description \"\" !hidden defaultformat \"\" sequence \"\" store \"\""},
                {"3b) not hidden policy defined as value w/o apostrophe",
                        "description \"\" !hidden defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" hidden false defaultformat \"\" sequence \"\" store \"\""},
                {"3c) not hidden policy defined as value with apostrophe",
                        "description \"\" !hidden defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" hidden \"FAlse\" defaultformat \"\" sequence \"\" store \"\""},
                {"3d) hidden policy",
                        "",
                        "description \"\" hidden defaultformat \"\" sequence \"\" store \"\""},
                {"3e) hidden hidden defined as value w/o apostrophe",
                        "description \"\" hidden defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" hidden TRUE defaultformat \"\" sequence \"\" store \"\""},
                {"3f) hidden policy defined as value with apostrophe",
                        "description \"\" hidden defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" hidden \"True\" defaultformat \"\" sequence \"\" store \"\""},
                // policy type
                {"4a) policy with one type",
                        "",
                        "description \"\" !hidden type \"abc\" defaultformat \"\" sequence \"\" store \"\""},
                {"4b) policy with all types",
                        "",
                        "description \"\" !hidden type all defaultformat \"\" sequence \"\" store \"\""},
                {"4c) policy with multiple types to test sorting",
                        "description \"\" !hidden type \"abc\" type \"def\" defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" !hidden type \"def\" type \"abc\" defaultformat \"\" sequence \"\" store \"\""},
                {"4d) policy with one type in old syntax",
                        "description \"\" !hidden type \"def\" defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" !hidden type {\"def\"} defaultformat \"\" sequence \"\" store \"\""},
                {"4d) policy with types in old syntax",
                        "description \"\" !hidden type \"abc\" type \"def\" defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" !hidden type {\"def\" \"abc\"} defaultformat \"\" sequence \"\" store \"\""},
                // policy format
                {"5a) policy with one format",
                        "",
                        "description \"\" !hidden format \"abc\" defaultformat \"\" sequence \"\" store \"\""},
                {"5b) policy with all formats",
                        "",
                        "description \"\" !hidden format all defaultformat \"\" sequence \"\" store \"\""},
                {"5c) policy with multiple formats to test sorting",
                        "description \"\" !hidden format \"abc\" format \"def\" defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" !hidden format \"def\" format \"abc\" defaultformat \"\" sequence \"\" store \"\""},
                {"5d) policy with one format in old syntax",
                        "description \"\" !hidden format \"def\" defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" !hidden format {\"def\"} defaultformat \"\" sequence \"\" store \"\""},
                {"5d) policy with formats in old syntax",
                        "description \"\" !hidden format \"abc\" format \"def\" defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" !hidden format {\"def\" \"abc\"} defaultformat \"\" sequence \"\" store \"\""},
                // enforce flag
                {"6a) not enforce policy",
                        "description \"\" !hidden defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" !hidden defaultformat \"\" !enforce sequence \"\" store \"\""},
                {"6b) not enforce policy defined as value w/o apostrophe",
                        "description \"\" !hidden defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" !hidden defaultformat \"\" enforce false sequence \"\" store \"\""},
                {"6c) not enforce policy defined as value with apostrophe",
                        "description \"\" !hidden defaultformat \"\" sequence \"\" store \"\"",
                        "description \"\" !hidden defaultformat \"\" enforce \"FAlse\" sequence \"\" store \"\""},
                {"6d) enforce policy",
                        "",
                        "description \"\" !hidden defaultformat \"\" enforce sequence \"\" store \"\""},
                {"6e) enforce policy defined as value w/o apostrophe",
                        "description \"\" !hidden defaultformat \"\" enforce sequence \"\" store \"\"",
                        "description \"\" !hidden defaultformat \"\" enforce TRUE sequence \"\" store \"\""},
                {"6f) enforce policy defined as value with apostrophe",
                        "description \"\" !hidden defaultformat \"\" enforce sequence \"\" store \"\"",
                        "description \"\" !hidden defaultformat \"\" enforce \"True\" sequence \"\" store \"\""},
                // special characters
                {"7a) policy with description special characters",
                        "",
                        "description \"{}\\\"\" hidden defaultformat \"\" sequence \"\" store \"\""},
                {"7b) policy with type special characters",
                        "",
                        "description \"\" hidden type \"{}\\\"\" defaultformat \"\" sequence \"\" store \"\""},
                {"7c) policy with format special characters",
                        "",
                        "description \"\" hidden format \"{}\\\"\" defaultformat \"\" sequence \"\" store \"\""},
                {"7d) policy with defaultformat special characters",
                        "",
                        "description \"\" hidden defaultformat \"{}\\\"\" sequence \"\" store \"\""},
                {"7e) policy with sequence special characters",
                        "",
                        "description \"\" hidden defaultformat \"\" sequence \"{}\\\"\" store \"\""},
                {"7f) policy with store special characters",
                        "",
                        "description \"\" hidden defaultformat \"\" sequence \"\" store \"{}\\\"\""},
                {"7g) policy with delimeter / minor special characters",
                        "",
                        "description \"\" hidden defaultformat \"\" delimiter \".\" minorsequence \"{}\\\"\" majorsequence \"{}\\\"\" store \"\""},
                // policy property
                {"8a) policy with property special characters",
                        "",
                        simple + "property \"{}\\\"\""},
                {"8b) policy with property and value special characters",
                        "",
                        simple + "property \"{}\\\"\" value \"{}\\\"\""},
                {"8c) policy with property link special characters",
                        "",
                        simple + "property \"{}\\\"\" to type \"{}\\\"\""},
                {"8d) policy with property link and value special characters",
                        "",
                        simple + "property \"{}\\\"\" to type \"{}\\\"\" value \"{}\\\"\""},
                // policy state with special characters
                {"9a) policy with state symbolic name special characters",
                        "",
                        simple + "state \"{}\\\"\" { registeredName \"{}\\\"\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"9b) policy with state action",
                        "",
                        simple + "state \"A\" { registeredName \"A\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published action \"AAA\" input \"\" }"},
                {"9c) policy with empty state action",
                        simple + "state \"A\" { registeredName \"A\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"A\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published action \"\" input \"\" }"},
                {"9d) policy with state action input",
                        "",
                        simple + "state \"A\" { registeredName \"A\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published action \"\" input \"AAA\" }"},
                {"9e) policy with state check",
                        "",
                        simple + "state \"A\" { registeredName \"A\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published check \"AAA\" input \"\" }"},
                {"9f) policy with empty state check",
                        simple + "state \"A\" { registeredName \"A\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"A\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published check \"\" input \"\" }"},
                {"9g) policy with state check input",
                        "",
                        simple + "state \"A\" { registeredName \"A\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published check \"\" input \"AAA\" }"},
                // policy state property
                {"10a) policy with state property special characters",
                        "",
                        simple + "state \"A\" { registeredName \"\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published property \"{}\\\"\" }"},
                {"10b) policy with state property and value special characters",
                        "",
                        simple + "state \"A\" { registeredName \"\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published property \"{}\\\"\" value \"{}\\\"\" }"},
                {"10c) policy with state property link special characters",
                        "",
                        simple + "state \"A\" { registeredName \"\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published property \"{}\\\"\" to type \"{}\\\"\" }"},
                {"10d) policy with state property link and value special characters",
                        "",
                        simple + "state \"A\" { registeredName \"\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published property \"{}\\\"\" to type \"{}\\\"\" value \"{}\\\"\" }"},
                // policy state with enforce flag
                {"11a) policy state not enforcereserveaccess",
                        "",
                        simple + "state \"A\" { registeredName \"\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"11b) policy state not enforcereserveaccess defined as not",
                        simple + "state \"A\" { registeredName \"\"   !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" notenforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"11c) policy state not enforcereserveaccess defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess false majorrevision minorrevision version promote checkouthistory published }"},
                {"11d) policy state not enforcereserveaccess defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" !enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess \"FAlse\" majorrevision minorrevision version promote checkouthistory published }"},
                {"11e) policy state enforcereserveaccess",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"11f) policy state enforcereserveaccess defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess TRUE majorrevision minorrevision version promote checkouthistory published }"},
                {"11g) policy state enforcereserveaccess defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess \"True\" majorrevision minorrevision version promote checkouthistory published }"},
                // policy state with majorrevision flag
                {"12a) policy state not majorrevision",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess !majorrevision minorrevision version promote checkouthistory published }"},
                {"12b) policy state not majorrevision defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess !majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision false minorrevision version promote checkouthistory published }"},
                {"12c) policy state not majorrevision defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess !majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision \"FAlse\" minorrevision version promote checkouthistory published }"},
                {"12d) policy state majorrevision",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"12e) policy state majorrevision defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision TRUE minorrevision version promote checkouthistory published }"},
                {"12f) policy state majorrevision defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision \"True\" minorrevision version promote checkouthistory published }"},
                // policy state with minorrevision flag
                {"13a) policy state not minorrevision",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision !minorrevision version promote checkouthistory published }"},
                {"13b) policy state not minorrevision defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision !minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision false version promote checkouthistory published }"},
                {"13c) policy state not minorrevision defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision !minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision \"FAlse\" version promote checkouthistory published }"},
                {"13d) policy state minorrevision",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"13e) policy state minorrevision defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision TRUE version promote checkouthistory published }"},
                {"13f) policy state minorrevision defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision \"True\" version promote checkouthistory published }"},
                // policy state with revision flag
                {"14a) policy state not revision",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision !minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision !revision version promote checkouthistory published }"},
                {"14b) policy state not minorrevision defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision !minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision revision false version promote checkouthistory published }"},
                {"14c) policy state not minorrevision defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision !minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision revision \"FAlse\" version promote checkouthistory published }"},
                {"14d) policy state minorrevision",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision revision version promote checkouthistory published }"},
                {"14e) policy state minorrevision defined as value w/o apostrophe",
                       simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision revision TRUE version promote checkouthistory published }"},
                {"14f) policy state minorrevision defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision revision \"True\" version promote checkouthistory published }"},
                // policy state with version flag
                {"15a) policy state not version",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision !version promote checkouthistory published }"},
                {"15b) policy state not version defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision !version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version false promote checkouthistory published }"},
                {"15c) policy state not version defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision !version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version \"FAlse\" promote checkouthistory published }"},
                {"15d) policy state version",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"15e) policy state version defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version TRUE promote checkouthistory published }"},
                {"15f) policy state version defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version \"True\" promote checkouthistory published }"},
                // policy state with promote flag
                {"16a) policy state not promote",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version !promote checkouthistory published }"},
                {"16b) policy state not promote defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version !promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote false checkouthistory published }"},
                {"16c) policy state not promote defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version !promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote \"FAlse\" checkouthistory published }"},
                {"16d) policy state promote",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"16e) policy state promote defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote TRUE checkouthistory published }"},
                {"16f) policy state promote defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote \"True\" checkouthistory published }"},
                // policy state with checkouthistory flag
                {"17a) policy state not checkouthistory",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote !checkouthistory published }"},
                {"17b) policy state not checkouthistory defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote !checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory false published }"},
                {"17c) policy state not checkouthistory defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote !checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory \"FAlse\" published }"},
                {"17d) policy state checkouthistory",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"17e) policy state checkouthistory defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory TRUE published }"},
                {"17f) policy state checkouthistory defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory \"True\" published }"},
                // policy state with published flag
                {"18a) policy state not published",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory !published }"},
                {"18b) policy state not published defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory !published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published false }"},
                {"18c) policy state not published defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory !published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published \"FAlse\" }"},
                {"18d) policy state published",
                        "",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }"},
                {"18e) policy state published defined as value w/o apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published TRUE }"},
                {"18f) policy state published defined as value with apostrophe",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published }",
                        simple + "state \"A\" { registeredName \"\" enforcereserveaccess majorrevision minorrevision version promote checkouthistory published \"True\" }"},

                // all state owner
                {"20a) all state owner", "", simple + "allstate {              owner             {read} }"},
                {"20b) all state owner", "", simple + "allstate {        login owner             {read} }"},
                {"20c) all state owner", "", simple + "allstate { revoke       owner             {read} }"},
                {"20d) all state owner", "", simple + "allstate { revoke login owner             {read} }"},
                {"20e) all state owner", "", simple + "allstate {              owner key \"key\" {read} }"},
                {"20f) all state owner", "", simple + "allstate {        login owner key \"key\" {read} }"},
                {"20g) all state owner", "", simple + "allstate { revoke       owner key \"key\" {read} }"},
                {"20h) all state owner", "", simple + "allstate { revoke login owner key \"key\" {read} }"},
                // all state public
                {"21a) all state public", "", simple + "allstate {              public             {read} }"},
                {"21b) all state public", "", simple + "allstate {        login public             {read} }"},
                {"21c) all state public", "", simple + "allstate { revoke       public             {read} }"},
                {"21d) all state public", "", simple + "allstate { revoke login public             {read} }"},
                {"21e) all state public", "", simple + "allstate {              public key \"key\" {read} }"},
                {"21f) all state public", "", simple + "allstate {        login public key \"key\" {read} }"},
                {"21g) all state public", "", simple + "allstate { revoke       public key \"key\" {read} }"},
                {"21h) all state public", "", simple + "allstate { revoke login public key \"key\" {read} }"},
                // allstate state user
                {"22a) all state user", "", simple + "allstate {              user \"createor\"             {read} }"},
                {"22b) all state user", "", simple + "allstate {        login user \"createor\"             {read} }"},
                {"22c) all state user", "", simple + "allstate { revoke       user \"createor\"             {read} }"},
                {"22d) all state user", "", simple + "allstate { revoke login user \"createor\"             {read} }"},
                {"22e) all state user", "", simple + "allstate {              user \"createor\" key \"key\" {read} }"},
                {"22f) all state user", "", simple + "allstate {        login user \"createor\" key \"key\" {read} }"},
                {"22g) all state user", "", simple + "allstate { revoke       user \"createor\" key \"key\" {read} }"},
                {"22h) all state user", "", simple + "allstate { revoke login user \"createor\" key \"key\" {read} }"},

                // single state owner
                {"30a) single state owner", "", simple + "state \"A\" { " + state + "              owner             {read} }"},
                {"30b) single state owner", "", simple + "state \"A\" { " + state + "        login owner             {read} }"},
                {"30c) single state owner", "", simple + "state \"A\" { " + state + " revoke       owner             {read} }"},
                {"30d) single state owner", "", simple + "state \"A\" { " + state + " revoke login owner             {read} }"},
                {"30e) single state owner", "", simple + "state \"A\" { " + state + "              owner key \"key\" {read} }"},
                {"30f) single state owner", "", simple + "state \"A\" { " + state + "        login owner key \"key\" {read} }"},
                {"30g) single state owner", "", simple + "state \"A\" { " + state + " revoke       owner key \"key\" {read} }"},
                {"30h) single state owner", "", simple + "state \"A\" { " + state + " revoke login owner key \"key\" {read} }"},
                // single state public
                {"31a) single state public", "", simple + "state \"A\" { " + state + "              public             {read} }"},
                {"31b) single state public", "", simple + "state \"A\" { " + state + "        login public             {read} }"},
                {"31c) single state public", "", simple + "state \"A\" { " + state + " revoke       public             {read} }"},
                {"31d) single state public", "", simple + "state \"A\" { " + state + " revoke login public             {read} }"},
                {"31e) single state public", "", simple + "state \"A\" { " + state + "              public key \"key\" {read} }"},
                {"31f) single state public", "", simple + "state \"A\" { " + state + "        login public key \"key\" {read} }"},
                {"31g) single state public", "", simple + "state \"A\" { " + state + " revoke       public key \"key\" {read} }"},
                {"31h) single state public", "", simple + "state \"A\" { " + state + " revoke login public key \"key\" {read} }"},
                // single state user
                {"32a) single state user", "", simple + "state \"A\" { " + state + "              user \"createor\"             {read} }"},
                {"32b) single state user", "", simple + "state \"A\" { " + state + "        login user \"createor\"             {read} }"},
                {"32c) single state user", "", simple + "state \"A\" { " + state + " revoke       user \"createor\"             {read} }"},
                {"32d) single state user", "", simple + "state \"A\" { " + state + " revoke login user \"createor\"             {read} }"},
                {"32e) single state user", "", simple + "state \"A\" { " + state + "              user \"createor\" key \"key\" {read} }"},
                {"32f) single state user", "", simple + "state \"A\" { " + state + "        login user \"createor\" key \"key\" {read} }"},
                {"32g) single state user", "", simple + "state \"A\" { " + state + " revoke       user \"createor\" key \"key\" {read} }"},
                {"32h) single state user", "", simple + "state \"A\" { " + state + " revoke login user \"createor\" key \"key\" {read} }"},

                // state route
                {"40a) state with route",                "", simple + "state \"A\" { " + state + " route {\"abc\"} \"\"     }"},
                {"40b) state with route & message",      "", simple + "state \"A\" { " + state + " route {\"abc\"} \"abc\"  }"},
                {"40c) state with multiple route users (to test sorting)",
                        simple + "state \"A\" { " + state + " route {\"abc\" \"def\"} \"\" }",
                        simple + "state \"A\" { " + state + " route {\"def\" \"abc\"} \"\" }"},
                {"40d) state with empty route user",
                        simple + "state \"A\" { " + state + "               }",
                        simple + "state \"A\" { " + state + " route {} \"\" }"},

                // state trigger
                {"50a) state with check trigger",               "", simple + "state \"A\" { " + state + " trigger modify check    \"Prog\" input \"\" }"},
                {"50b) state with check trigger & input",       "", simple + "state \"A\" { " + state + " trigger modify check    \"Prog\" input \"abc\" }"},
                {"50c) state with check trigger & empty input",
                        simple + "state \"A\" { " + state + " trigger modify check    \"Prog\" input \"\" }",
                        simple + "state \"A\" { " + state + " trigger modify check    \"Prog\"            }"},
                {"51a) state with override trigger",         "", simple + "state \"A\" { " + state + " trigger modify override \"Prog\" input \"\" }"},
                {"51b) state with override trigger & input", "", simple + "state \"A\" { " + state + " trigger modify override \"Prog\" input \"abc\" }"},
                {"51c) state with check trigger & empty input",
                        simple + "state \"A\" { " + state + " trigger modify override    \"Prog\" input \"\" }",
                        simple + "state \"A\" { " + state + " trigger modify override    \"Prog\"            }"},

                {"52a) state with action trigger",           "", simple + "state \"A\" { " + state + " trigger modify action   \"Prog\" input \"\" }"},
                {"52b) state with action trigger & input",   "", simple + "state \"A\" { " + state + " trigger modify action   \"Prog\" input \"abc\" }"},
                {"52c) state with check trigger & no input",
                        simple + "state \"A\" { " + state + " trigger modify action    \"Prog\" input \"\" }",
                        simple + "state \"A\" { " + state + " trigger modify action    \"Prog\"             }"},

                // state signature (branch)
                {"60a) state with signature",         "", simple + "state \"A\" { " + state + " signature \"A\" { branch \"\"    approve {}        ignore {}        reject {}        filter \"\"    } }"},
                {"60b) state with signature branch",  "", simple + "state \"A\" { " + state + " signature \"A\" { branch \"abc\" approve {}        ignore {}        reject {}        filter \"\"    } }"},
                {"60c) state with signature approve", "", simple + "state \"A\" { " + state + " signature \"A\" { branch \"\"    approve {\"abc\"} ignore {}        reject {}        filter \"\"    } }"},
                {"60d) state with signature ignore",  "", simple + "state \"A\" { " + state + " signature \"A\" { branch \"\"    approve {}        ignore {\"abc\"} reject {}        filter \"\"    } }"},
                {"60e) state with signature reject",  "", simple + "state \"A\" { " + state + " signature \"A\" { branch \"\"    approve {}        ignore {}        reject {\"abc\"} filter \"\"    } }"},
                {"60f) state with signature filter",  "", simple + "state \"A\" { " + state + " signature \"A\" { branch \"\"    approve {}        ignore {}        reject {}        filter \"abc\" } }"},
                {"60g) state with empty signature value (to check default values)",
                        simple + "state \"A\" { " + state + " signature \"A\" { branch \"\" approve {} ignore {} reject {} filter \"\" } }",
                        simple + "state \"A\" { " + state + " signature \"A\" { } }"},
        };
    }

    @Override()
    protected Policy_mxJPO createNewData(final ParameterCache_mxJPO _paramCache,
                                         final String _name)
    {
        return new Policy_mxJPO(_paramCache.getMapping().getTypeDef(CI.DM_POLICY.updateType), _name);
    }
}
