/* Generated By:JavaCC: Do not edit this line. MxParserConstants.java */
/*
 *  This file is part of MxUpdate <http://www.mxupdate.org>.
 *
 *  MxUpdate is a deployment tool for a PLM platform to handle
 *  administration objects as single update files (configuration item).
 *
 *  Copyright (C) 2008-2016 The MxUpdate Team - All Rights Reserved
 *
 *  You may use, distribute and modify MxUpdate under the terms of the
 *  MxUpdate license. You should have received a copy of the MxUpdate
 *  license with this file. If not, please write to <info@mxupdate.org>,
 *  or visit <www.mxupdate.org>.
 *
 */

package org.mxupdate.update.zparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface MxParserConstants_mxJPO {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PACKAGE = 5;
  /** RegularExpression Id. */
  int UUID = 6;
  /** RegularExpression Id. */
  int SYMBOLICNAME = 7;
  /** RegularExpression Id. */
  int ACTIVE_TRUE = 8;
  /** RegularExpression Id. */
  int ACTIVE_FALSE = 9;
  /** RegularExpression Id. */
  int HIDDEN_TRUE = 10;
  /** RegularExpression Id. */
  int HIDDEN_FALSE = 11;
  /** RegularExpression Id. */
  int TREEMENU_TRUE = 12;
  /** RegularExpression Id. */
  int TREEMENU_FALSE = 13;
  /** RegularExpression Id. */
  int TRUSTED_TRUE = 14;
  /** RegularExpression Id. */
  int TRUSTED_FALSE = 15;
  /** RegularExpression Id. */
  int EMAIL_TRUE = 16;
  /** RegularExpression Id. */
  int EMAIL_FALSE = 17;
  /** RegularExpression Id. */
  int INCONMAIL_TRUE = 18;
  /** RegularExpression Id. */
  int INCONMAIL_FALSE = 19;
  /** RegularExpression Id. */
  int HEIGHT = 20;
  /** RegularExpression Id. */
  int USER = 21;
  /** RegularExpression Id. */
  int SETTING = 22;
  /** RegularExpression Id. */
  int ARGUMENT = 23;
  /** RegularExpression Id. */
  int CHANNEL = 24;
  /** RegularExpression Id. */
  int COMMAND = 25;
  /** RegularExpression Id. */
  int MENU = 26;
  /** RegularExpression Id. */
  int NEWROW = 27;
  /** RegularExpression Id. */
  int ADDRESS = 28;
  /** RegularExpression Id. */
  int ALT = 29;
  /** RegularExpression Id. */
  int APPLICATION = 30;
  /** RegularExpression Id. */
  int DEFINITION = 31;
  /** RegularExpression Id. */
  int EMAILADDRESS = 32;
  /** RegularExpression Id. */
  int FAX = 33;
  /** RegularExpression Id. */
  int FORMAT = 34;
  /** RegularExpression Id. */
  int FULLNAME = 35;
  /** RegularExpression Id. */
  int GROUP = 36;
  /** RegularExpression Id. */
  int HREF = 37;
  /** RegularExpression Id. */
  int LABEL = 38;
  /** RegularExpression Id. */
  int PARENT = 39;
  /** RegularExpression Id. */
  int PATTERN = 40;
  /** RegularExpression Id. */
  int PHONE = 41;
  /** RegularExpression Id. */
  int ROLE = 42;
  /** RegularExpression Id. */
  int SITE = 43;
  /** RegularExpression Id. */
  int VAULT = 44;
  /** RegularExpression Id. */
  int CODE = 45;
  /** RegularExpression Id. */
  int COMMENT = 46;
  /** RegularExpression Id. */
  int DESCRIPTION = 47;
  /** RegularExpression Id. */
  int STRING_STRING_STRING = 48;
  /** RegularExpression Id. */
  int STRING_STRING_SINGLE = 49;
  /** RegularExpression Id. */
  int STRING = 50;
  /** RegularExpression Id. */
  int SINGLE = 51;
  /** RegularExpression Id. */
  int MULTILINESTRING = 52;
  /** RegularExpression Id. */
  int MULTILINESINGLE = 53;
  /** RegularExpression Id. */
  int NATURALNUMBER = 54;
  /** RegularExpression Id. */
  int ACCESS = 55;
  /** RegularExpression Id. */
  int ACCESS_ALL = 56;
  /** RegularExpression Id. */
  int ACCESS_OPEN = 57;
  /** RegularExpression Id. */
  int ACCESS_CLOSE = 58;
  /** RegularExpression Id. */
  int ACCESS_EXPECTED_SINGLE = 59;
  /** RegularExpression Id. */
  int ADMIN = 60;
  /** RegularExpression Id. */
  int ADMIN_ALL = 61;
  /** RegularExpression Id. */
  int ADMIN_OPEN = 62;
  /** RegularExpression Id. */
  int ADMIN_CLOSE = 63;
  /** RegularExpression Id. */
  int ADMIN_EXPECTED_SINGLE = 64;
  /** RegularExpression Id. */
  int PRODUCT = 65;
  /** RegularExpression Id. */
  int PRODUCT_OPEN = 66;
  /** RegularExpression Id. */
  int PRODUCT_CLOSE = 67;
  /** RegularExpression Id. */
  int PRODUCT_EXPECTED_SINGLE = 68;
  /** RegularExpression Id. */
  int TYPE = 69;
  /** RegularExpression Id. */
  int TYPE_OPEN = 70;
  /** RegularExpression Id. */
  int TYPE_CLOSE = 71;
  /** RegularExpression Id. */
  int TYPE_APPLICATION = 72;
  /** RegularExpression Id. */
  int TYPE_FULL = 73;
  /** RegularExpression Id. */
  int TYPE_BUSINESS = 74;
  /** RegularExpression Id. */
  int TYPE_SYSTEM = 75;
  /** RegularExpression Id. */
  int FIELD = 76;
  /** RegularExpression Id. */
  int FIELD_OPEN = 77;
  /** RegularExpression Id. */
  int FIELD_CLOSE = 78;
  /** RegularExpression Id. */
  int FIELD_NAME = 79;
  /** RegularExpression Id. */
  int FIELD_LABEL = 80;
  /** RegularExpression Id. */
  int FIELD_SELECT = 81;
  /** RegularExpression Id. */
  int FIELD_BOBJ = 82;
  /** RegularExpression Id. */
  int FIELD_REL = 83;
  /** RegularExpression Id. */
  int FIELD_RANGE = 84;
  /** RegularExpression Id. */
  int FIELD_HREF = 85;
  /** RegularExpression Id. */
  int FIELD_ALT = 86;
  /** RegularExpression Id. */
  int FIELD_USER = 87;
  /** RegularExpression Id. */
  int FIELD_SETTING = 88;
  /** RegularExpression Id. */
  int FIELD_STRING = 89;
  /** RegularExpression Id. */
  int FIELD_SINGLE = 90;
  /** RegularExpression Id. */
  int FIELD_SETTING_STRING = 91;
  /** RegularExpression Id. */
  int FIELD_SETTING_SINGLE = 92;
  /** RegularExpression Id. */
  int COLUMN = 93;
  /** RegularExpression Id. */
  int COLUMN_OPEN = 94;
  /** RegularExpression Id. */
  int COLUMN_CLOSE = 95;
  /** RegularExpression Id. */
  int COLUMN_NAME = 96;
  /** RegularExpression Id. */
  int COLUMN_LABEL = 97;
  /** RegularExpression Id. */
  int COLUMN_SELECT = 98;
  /** RegularExpression Id. */
  int COLUMN_BOBJ = 99;
  /** RegularExpression Id. */
  int COLUMN_REL = 100;
  /** RegularExpression Id. */
  int COLUMN_RANGE = 101;
  /** RegularExpression Id. */
  int COLUMN_HREF = 102;
  /** RegularExpression Id. */
  int COLUMN_ALT = 103;
  /** RegularExpression Id. */
  int COLUMN_HIDDEN_TRUE = 104;
  /** RegularExpression Id. */
  int COLUMN_HIDDEN_FALSE = 105;
  /** RegularExpression Id. */
  int COLUMN_USER = 106;
  /** RegularExpression Id. */
  int COLUMN_SORTTYPE = 107;
  /** RegularExpression Id. */
  int COLUMN_SETTING = 108;
  /** RegularExpression Id. */
  int COLUMN_STRING = 109;
  /** RegularExpression Id. */
  int COLUMN_SINGLE = 110;
  /** RegularExpression Id. */
  int SETTING_STRING = 111;
  /** RegularExpression Id. */
  int SETTING_SINGLE = 112;
  /** RegularExpression Id. */
  int COLUMN_SORTTYPE_ALPHA = 113;
  /** RegularExpression Id. */
  int COLUMN_SORTTYPE_NUMERIC = 114;
  /** RegularExpression Id. */
  int COLUMN_SORTTYPE_OTHER = 115;
  /** RegularExpression Id. */
  int COLUMN_SORTTYPE_NONE = 116;
  /** RegularExpression Id. */
  int PROPERTY = 117;
  /** RegularExpression Id. */
  int PROPERTYTO = 118;
  /** RegularExpression Id. */
  int PROPERTYVAL = 119;

  /** Lexical state. */
  int COLUMN_SORTTYPE_EXPECTED = 0;
  /** Lexical state. */
  int COLUMN_SETTING_STRING_EXPECTED = 1;
  /** Lexical state. */
  int COLUMN_STRING_EXPECTED = 2;
  /** Lexical state. */
  int COLUMN_EXPECTED = 3;
  /** Lexical state. */
  int COLUMN_OPENEXPECTED = 4;
  /** Lexical state. */
  int FIELD_SETTING_EXPECTED = 5;
  /** Lexical state. */
  int FIELD_STRING_EXPECTED = 6;
  /** Lexical state. */
  int FIELD_EXPECTED = 7;
  /** Lexical state. */
  int FIELD_OPENEXPECTED = 8;
  /** Lexical state. */
  int TYPE_EXPECTED = 9;
  /** Lexical state. */
  int TYPE_OPENEXPECTED = 10;
  /** Lexical state. */
  int PRODUCT_EXPECTED = 11;
  /** Lexical state. */
  int PRODUCT_OPENEXPECTED = 12;
  /** Lexical state. */
  int ADMIN_EXPECTED = 13;
  /** Lexical state. */
  int ADMIN_OPENEXPECTED = 14;
  /** Lexical state. */
  int ACCESS_EXPECTED = 15;
  /** Lexical state. */
  int ACCESS_OPENEXPECTED = 16;
  /** Lexical state. */
  int NATURALNUMBER_EXPECTED = 17;
  /** Lexical state. */
  int MULTILINESTRING_EXPECTED = 18;
  /** Lexical state. */
  int STRING_EXPECTED = 19;
  /** Lexical state. */
  int STRING_STRING_EXPECTED = 20;
  /** Lexical state. */
  int DEFAULT = 21;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 4>",
    "\"package\"",
    "\"uuid\"",
    "\"symbolicname\"",
    "\"active\"",
    "\"!active\"",
    "\"hidden\"",
    "\"!hidden\"",
    "\"treemenu\"",
    "\"!treemenu\"",
    "\"trusted\"",
    "\"!trusted\"",
    "\"email\"",
    "\"!email\"",
    "\"iconmail\"",
    "\"!iconmail\"",
    "\"height\"",
    "<USER>",
    "<SETTING>",
    "\"argument\"",
    "\"channel\"",
    "<COMMAND>",
    "<MENU>",
    "\"newrow\"",
    "\"address\"",
    "\"alt\"",
    "\"application\"",
    "\"definition\"",
    "\"emailaddress\"",
    "\"fax\"",
    "\"format\"",
    "\"fullname\"",
    "\"group\"",
    "\"href\"",
    "\"label\"",
    "\"parent\"",
    "\"pattern\"",
    "\"phone\"",
    "\"role\"",
    "\"site\"",
    "\"vault\"",
    "\"code\"",
    "\"comment\"",
    "\"description\"",
    "<STRING_STRING_STRING>",
    "<STRING_STRING_SINGLE>",
    "<STRING>",
    "<SINGLE>",
    "<MULTILINESTRING>",
    "<MULTILINESINGLE>",
    "<NATURALNUMBER>",
    "\"access\"",
    "\"all\"",
    "\"{\"",
    "\"}\"",
    "<ACCESS_EXPECTED_SINGLE>",
    "\"admin\"",
    "\"all\"",
    "\"{\"",
    "\"}\"",
    "<ADMIN_EXPECTED_SINGLE>",
    "\"product\"",
    "\"{\"",
    "\"}\"",
    "<PRODUCT_EXPECTED_SINGLE>",
    "\"type\"",
    "\"{\"",
    "\"}\"",
    "\"application\"",
    "\"full\"",
    "\"business\"",
    "\"system\"",
    "\"field\"",
    "\"{\"",
    "\"}\"",
    "\"name\"",
    "\"label\"",
    "\"select\"",
    "\"businessobject\"",
    "\"relationship\"",
    "\"range\"",
    "\"href\"",
    "\"alt\"",
    "\"user\"",
    "\"setting\"",
    "<FIELD_STRING>",
    "<FIELD_SINGLE>",
    "<FIELD_SETTING_STRING>",
    "<FIELD_SETTING_SINGLE>",
    "\"column\"",
    "\"{\"",
    "\"}\"",
    "\"name\"",
    "\"label\"",
    "\"select\"",
    "\"businessobject\"",
    "\"relationship\"",
    "\"range\"",
    "\"href\"",
    "\"alt\"",
    "\"hidden\"",
    "\"!hidden\"",
    "\"user\"",
    "\"sorttype\"",
    "\"setting\"",
    "<COLUMN_STRING>",
    "<COLUMN_SINGLE>",
    "<SETTING_STRING>",
    "<SETTING_SINGLE>",
    "\"alpha\"",
    "\"numeric\"",
    "\"other\"",
    "\"none\"",
    "\"property\"",
    "\"to\"",
    "\"value\"",
  };

}
