/* Generated By:JavaCC: Do not edit this line. AttributeParserConstants.java */
package org.mxupdate.update.datamodel;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface AttributeParserConstants_mxJPO {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SYMBOLICNAME = 5;
  /** RegularExpression Id. */
  int DESCRIPTION = 6;
  /** RegularExpression Id. */
  int DEFAULTVALUE = 7;
  /** RegularExpression Id. */
  int HIDDEN_TRUE = 8;
  /** RegularExpression Id. */
  int HIDDEN_FALSE = 9;
  /** RegularExpression Id. */
  int MULTIVALUE_TRUE = 10;
  /** RegularExpression Id. */
  int MULTIVALUE_FALSE = 11;
  /** RegularExpression Id. */
  int RESETONCLONE_TRUE = 12;
  /** RegularExpression Id. */
  int RESETONCLONE_FALSE = 13;
  /** RegularExpression Id. */
  int RESETONREVISION_TRUE = 14;
  /** RegularExpression Id. */
  int RESETONREVISION_FALSE = 15;
  /** RegularExpression Id. */
  int RANGEVALUE_TRUE = 16;
  /** RegularExpression Id. */
  int RANGEVALUE_FALSE = 17;
  /** RegularExpression Id. */
  int MULTILINE_TRUE = 18;
  /** RegularExpression Id. */
  int MULTILINE_FALSE = 19;
  /** RegularExpression Id. */
  int MAXLENGTH = 20;
  /** RegularExpression Id. */
  int RULE = 21;
  /** RegularExpression Id. */
  int DIMENSION = 22;
  /** RegularExpression Id. */
  int INPUT = 23;
  /** RegularExpression Id. */
  int STRING = 24;
  /** RegularExpression Id. */
  int SINGLE = 25;
  /** RegularExpression Id. */
  int MULTILINESTRING = 26;
  /** RegularExpression Id. */
  int MULTILINESINGLE = 27;
  /** RegularExpression Id. */
  int MAXLENGTH_NUMBER = 28;
  /** RegularExpression Id. */
  int TRIGGER = 29;
  /** RegularExpression Id. */
  int TRIGEVENT = 30;
  /** RegularExpression Id. */
  int ACTION = 31;
  /** RegularExpression Id. */
  int CHECK = 32;
  /** RegularExpression Id. */
  int OVERRIDE = 33;
  /** RegularExpression Id. */
  int RANGE_EQUAL = 34;
  /** RegularExpression Id. */
  int RANGE_GREATERTHAN = 35;
  /** RegularExpression Id. */
  int RANGE_GREATERTHANEQUAL = 36;
  /** RegularExpression Id. */
  int RANGE_LESSTHAN = 37;
  /** RegularExpression Id. */
  int RANGE_LESSTHANEQUAL = 38;
  /** RegularExpression Id. */
  int RANGE_NOTEQUAL = 39;
  /** RegularExpression Id. */
  int RANGE_MATCH = 40;
  /** RegularExpression Id. */
  int RANGE_NOTMATCH = 41;
  /** RegularExpression Id. */
  int RANGE_SMATCH = 42;
  /** RegularExpression Id. */
  int RANGE_NOTSMATCH = 43;
  /** RegularExpression Id. */
  int RANGE_PROGRAM = 44;
  /** RegularExpression Id. */
  int RANGE_BETWEEN = 45;
  /** RegularExpression Id. */
  int BETW1_STRING = 46;
  /** RegularExpression Id. */
  int BETW1_SINGLE = 47;
  /** RegularExpression Id. */
  int BETW1_APOSTROPHE = 48;
  /** RegularExpression Id. */
  int BETW1_CHAR = 49;
  /** RegularExpression Id. */
  int BETW2_INCLUSIVE = 50;
  /** RegularExpression Id. */
  int BETW2_EXCLUSIVE = 51;
  /** RegularExpression Id. */
  int BETW3_STRING = 52;
  /** RegularExpression Id. */
  int BETW3_SINGLE = 53;
  /** RegularExpression Id. */
  int BETW3_APOSTROPHE = 54;
  /** RegularExpression Id. */
  int BETW3_CHAR = 55;
  /** RegularExpression Id. */
  int BETW4_INCLUSIVE = 56;
  /** RegularExpression Id. */
  int BETW4_EXCLUSIVE = 57;
  /** RegularExpression Id. */
  int PROPERTY = 58;
  /** RegularExpression Id. */
  int PROPERTYTO = 59;
  /** RegularExpression Id. */
  int PROPERTYVAL = 60;
  /** RegularExpression Id. */
  int ADMINTYPE_STRING = 61;
  /** RegularExpression Id. */
  int ADMINTYPE_SINGLE = 62;

  /** Lexical state. */
  int ADMINREF_EXPECTED = 0;
  /** Lexical state. */
  int BETW4_EXPECTED = 1;
  /** Lexical state. */
  int BETW3_EXPECTED = 2;
  /** Lexical state. */
  int BETW2_EXPECTED = 3;
  /** Lexical state. */
  int BETW1_EXPECTED = 4;
  /** Lexical state. */
  int TRIGKIND_EXPECTED = 5;
  /** Lexical state. */
  int TRIGEVENT_EXPECTED = 6;
  /** Lexical state. */
  int MAXLENGTH_EXPECTED = 7;
  /** Lexical state. */
  int MULTILINESTRING_EXPECTED = 8;
  /** Lexical state. */
  int STRING_EXPECTED = 9;
  /** Lexical state. */
  int DEFAULT = 10;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 4>",
    "\"symbolicname\"",
    "\"description\"",
    "\"default\"",
    "\"hidden\"",
    "\"!hidden\"",
    "\"multivalue\"",
    "\"!multivalue\"",
    "\"resetonclone\"",
    "\"!resetonclone\"",
    "\"resetonrevision\"",
    "\"!resetonrevision\"",
    "\"rangevalue\"",
    "\"!rangevalue\"",
    "\"multiline\"",
    "\"!multiline\"",
    "\"maxlength\"",
    "\"rule\"",
    "\"dimension\"",
    "\"input\"",
    "<STRING>",
    "<SINGLE>",
    "<MULTILINESTRING>",
    "<MULTILINESINGLE>",
    "<MAXLENGTH_NUMBER>",
    "\"trigger\"",
    "<TRIGEVENT>",
    "\"action\"",
    "\"check\"",
    "\"override\"",
    "<RANGE_EQUAL>",
    "<RANGE_GREATERTHAN>",
    "<RANGE_GREATERTHANEQUAL>",
    "<RANGE_LESSTHAN>",
    "<RANGE_LESSTHANEQUAL>",
    "<RANGE_NOTEQUAL>",
    "<RANGE_MATCH>",
    "<RANGE_NOTMATCH>",
    "<RANGE_SMATCH>",
    "<RANGE_NOTSMATCH>",
    "<RANGE_PROGRAM>",
    "<RANGE_BETWEEN>",
    "<BETW1_STRING>",
    "<BETW1_SINGLE>",
    "\"\\\"\"",
    "<BETW1_CHAR>",
    "\"inclusive\"",
    "\"exclusive\"",
    "<BETW3_STRING>",
    "<BETW3_SINGLE>",
    "\"\\\"\"",
    "<BETW3_CHAR>",
    "\"inclusive\"",
    "\"exclusive\"",
    "\"property\"",
    "\"to\"",
    "\"value\"",
    "<ADMINTYPE_STRING>",
    "<ADMINTYPE_SINGLE>",
  };

}
