/* Generated By:JavaCC: Do not edit this line. TypeParserConstants.java */
/*
 *  This file is part of MxUpdate <http://www.mxupdate.org>.
 *
 *  MxUpdate is a deployment tool for a PLM platform to handle
 *  administration objects as single update files (configuration item).
 *
 *  Copyright (C) 2008-2016 The MxUpdate Team - All Rights Reserved
 *
 *  You may use, distribute and modify MxUpdate under the terms of the
 *  MxUpdate license. You should have received a copy of the MxUpdate
 *  license with this file. If not, please write to <info@mxupdate.org>,
 *  or visit <www.mxupdate.org>.
 *
 */

package org.mxupdate.update.datamodel;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface TypeParserConstants_mxJPO {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int UUID = 5;
  /** RegularExpression Id. */
  int SYMBOLICNAME = 6;
  /** RegularExpression Id. */
  int DESCRIPTION = 7;
  /** RegularExpression Id. */
  int ABSTRACT_TRUE = 8;
  /** RegularExpression Id. */
  int ABSTRACT_FALSE = 9;
  /** RegularExpression Id. */
  int DERIVED = 10;
  /** RegularExpression Id. */
  int HIDDEN_TRUE = 11;
  /** RegularExpression Id. */
  int HIDDEN_FALSE = 12;
  /** RegularExpression Id. */
  int METHOD = 13;
  /** RegularExpression Id. */
  int STRING = 14;
  /** RegularExpression Id. */
  int SINGLE = 15;
  /** RegularExpression Id. */
  int MULTILINESTRING = 16;
  /** RegularExpression Id. */
  int MULTILINESINGLE = 17;
  /** RegularExpression Id. */
  int KIND = 18;
  /** RegularExpression Id. */
  int BASIC = 19;
  /** RegularExpression Id. */
  int COMPOSED = 20;
  /** RegularExpression Id. */
  int KIND_BINARY = 21;
  /** RegularExpression Id. */
  int KIND_BOOLEAN = 22;
  /** RegularExpression Id. */
  int KIND_DATE = 23;
  /** RegularExpression Id. */
  int KIND_INTEGER = 24;
  /** RegularExpression Id. */
  int KIND_REAL = 25;
  /** RegularExpression Id. */
  int KIND_STRING = 26;
  /** RegularExpression Id. */
  int GLOBAL_ATTRIBUTE = 27;
  /** RegularExpression Id. */
  int LOCAL_ATTRIBUTE = 28;
  /** RegularExpression Id. */
  int DEFAULTVALUE = 29;
  /** RegularExpression Id. */
  int MULTIVALUE_TRUE = 30;
  /** RegularExpression Id. */
  int MULTIVALUE_FALSE = 31;
  /** RegularExpression Id. */
  int RESETONCLONE_TRUE = 32;
  /** RegularExpression Id. */
  int RESETONCLONE_FALSE = 33;
  /** RegularExpression Id. */
  int RESETONREVISION_TRUE = 34;
  /** RegularExpression Id. */
  int RESETONREVISION_FALSE = 35;
  /** RegularExpression Id. */
  int RANGEVALUE_TRUE = 36;
  /** RegularExpression Id. */
  int RANGEVALUE_FALSE = 37;
  /** RegularExpression Id. */
  int MULTILINE_TRUE = 38;
  /** RegularExpression Id. */
  int MULTILINE_FALSE = 39;
  /** RegularExpression Id. */
  int RULE = 40;
  /** RegularExpression Id. */
  int DIMENSION = 41;
  /** RegularExpression Id. */
  int MAXLENGTH = 42;
  /** RegularExpression Id. */
  int MAXLENGTH_NUMBER = 43;
  /** RegularExpression Id. */
  int RANGE_EQUAL = 44;
  /** RegularExpression Id. */
  int RANGE_GREATERTHAN = 45;
  /** RegularExpression Id. */
  int RANGE_GREATERTHANEQUAL = 46;
  /** RegularExpression Id. */
  int RANGE_LESSTHAN = 47;
  /** RegularExpression Id. */
  int RANGE_LESSTHANEQUAL = 48;
  /** RegularExpression Id. */
  int RANGE_NOTEQUAL = 49;
  /** RegularExpression Id. */
  int RANGE_MATCH = 50;
  /** RegularExpression Id. */
  int RANGE_NOTMATCH = 51;
  /** RegularExpression Id. */
  int RANGE_SMATCH = 52;
  /** RegularExpression Id. */
  int RANGE_NOTSMATCH = 53;
  /** RegularExpression Id. */
  int RANGE_PROGRAM = 54;
  /** RegularExpression Id. */
  int RANGE_BETWEEN = 55;
  /** RegularExpression Id. */
  int BETW1_STRING = 56;
  /** RegularExpression Id. */
  int BETW1_SINGLE = 57;
  /** RegularExpression Id. */
  int BETW1_APOSTROPHE = 58;
  /** RegularExpression Id. */
  int BETW1_CHAR = 59;
  /** RegularExpression Id. */
  int BETW2_INCLUSIVE = 60;
  /** RegularExpression Id. */
  int BETW2_EXCLUSIVE = 61;
  /** RegularExpression Id. */
  int BETW3_STRING = 62;
  /** RegularExpression Id. */
  int BETW3_SINGLE = 63;
  /** RegularExpression Id. */
  int BETW3_APOSTROPHE = 64;
  /** RegularExpression Id. */
  int BETW3_CHAR = 65;
  /** RegularExpression Id. */
  int BETW4_INCLUSIVE = 66;
  /** RegularExpression Id. */
  int BETW4_EXCLUSIVE = 67;
  /** RegularExpression Id. */
  int LOCAL_PATHTYPE = 68;
  /** RegularExpression Id. */
  int FROM = 69;
  /** RegularExpression Id. */
  int TO = 70;
  /** RegularExpression Id. */
  int CARDINALITY_ONE = 71;
  /** RegularExpression Id. */
  int CARDINALITY_MANY = 72;
  /** RegularExpression Id. */
  int TYPE_ALL = 73;
  /** RegularExpression Id. */
  int TYPE = 74;
  /** RegularExpression Id. */
  int RELATIONSHIP_ALL = 75;
  /** RegularExpression Id. */
  int RELATIONSHIP = 76;
  /** RegularExpression Id. */
  int TRIGGER = 77;
  /** RegularExpression Id. */
  int INPUT = 78;
  /** RegularExpression Id. */
  int TRIGEVENT = 79;
  /** RegularExpression Id. */
  int ACTION = 80;
  /** RegularExpression Id. */
  int CHECK = 81;
  /** RegularExpression Id. */
  int OVERRIDE = 82;
  /** RegularExpression Id. */
  int PROPERTY = 83;
  /** RegularExpression Id. */
  int PROPERTYTO = 84;
  /** RegularExpression Id. */
  int PROPERTYVAL = 85;
  /** RegularExpression Id. */
  int ADMINTYPE_STRING = 86;
  /** RegularExpression Id. */
  int ADMINTYPE_SINGLE = 87;

  /** Lexical state. */
  int ADMINREF_EXPECTED = 0;
  /** Lexical state. */
  int TRIGKIND_EXPECTED = 1;
  /** Lexical state. */
  int TRIGEVENT_EXPECTED = 2;
  /** Lexical state. */
  int BETW4_EXPECTED = 3;
  /** Lexical state. */
  int BETW3_EXPECTED = 4;
  /** Lexical state. */
  int BETW2_EXPECTED = 5;
  /** Lexical state. */
  int BETW1_EXPECTED = 6;
  /** Lexical state. */
  int MAXLENGTH_EXPECTED = 7;
  /** Lexical state. */
  int KIND_EXPECTED = 8;
  /** Lexical state. */
  int MULTILINESTRING_EXPECTED = 9;
  /** Lexical state. */
  int STRING_EXPECTED = 10;
  /** Lexical state. */
  int DEFAULT = 11;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 4>",
    "\"uuid\"",
    "\"symbolicname\"",
    "\"description\"",
    "\"abstract\"",
    "\"!abstract\"",
    "\"derived\"",
    "\"hidden\"",
    "\"!hidden\"",
    "\"method\"",
    "<STRING>",
    "<SINGLE>",
    "<MULTILINESTRING>",
    "<MULTILINESINGLE>",
    "\"kind\"",
    "\"basic\"",
    "\"composed\"",
    "\"binary\"",
    "\"boolean\"",
    "\"date\"",
    "\"integer\"",
    "\"real\"",
    "\"string\"",
    "\"attribute\"",
    "<LOCAL_ATTRIBUTE>",
    "\"default\"",
    "\"multivalue\"",
    "\"!multivalue\"",
    "\"resetonclone\"",
    "\"!resetonclone\"",
    "\"resetonrevision\"",
    "\"!resetonrevision\"",
    "\"rangevalue\"",
    "\"!rangevalue\"",
    "\"multiline\"",
    "\"!multiline\"",
    "\"rule\"",
    "\"dimension\"",
    "\"maxlength\"",
    "<MAXLENGTH_NUMBER>",
    "<RANGE_EQUAL>",
    "<RANGE_GREATERTHAN>",
    "<RANGE_GREATERTHANEQUAL>",
    "<RANGE_LESSTHAN>",
    "<RANGE_LESSTHANEQUAL>",
    "<RANGE_NOTEQUAL>",
    "<RANGE_MATCH>",
    "<RANGE_NOTMATCH>",
    "<RANGE_SMATCH>",
    "<RANGE_NOTSMATCH>",
    "<RANGE_PROGRAM>",
    "<RANGE_BETWEEN>",
    "<BETW1_STRING>",
    "<BETW1_SINGLE>",
    "\"\\\"\"",
    "<BETW1_CHAR>",
    "\"inclusive\"",
    "\"exclusive\"",
    "<BETW3_STRING>",
    "<BETW3_SINGLE>",
    "\"\\\"\"",
    "<BETW3_CHAR>",
    "\"inclusive\"",
    "\"exclusive\"",
    "<LOCAL_PATHTYPE>",
    "<FROM>",
    "<TO>",
    "<CARDINALITY_ONE>",
    "<CARDINALITY_MANY>",
    "<TYPE_ALL>",
    "\"type\"",
    "<RELATIONSHIP_ALL>",
    "\"relationship\"",
    "\"trigger\"",
    "\"input\"",
    "<TRIGEVENT>",
    "\"action\"",
    "\"check\"",
    "\"override\"",
    "\"property\"",
    "\"to\"",
    "\"value\"",
    "<ADMINTYPE_STRING>",
    "<ADMINTYPE_SINGLE>",
    "\"{\"",
    "\"}\"",
  };

}
