/* Generated By:JavaCC: Do not edit this line. MenuDefParserConstants.java */
package org.mxupdate.update.userinterface.menu;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MenuDefParserConstants_mxJPO {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DESCRIPTION = 5;
  /** RegularExpression Id. */
  int HIDDEN_TRUE = 6;
  /** RegularExpression Id. */
  int HIDDEN_FALSE = 7;
  /** RegularExpression Id. */
  int TREEMENU_TRUE = 8;
  /** RegularExpression Id. */
  int TREEMENU_FALSE = 9;
  /** RegularExpression Id. */
  int ALT = 10;
  /** RegularExpression Id. */
  int HREF = 11;
  /** RegularExpression Id. */
  int LABEL = 12;
  /** RegularExpression Id. */
  int SETTING = 13;
  /** RegularExpression Id. */
  int COMMAND = 14;
  /** RegularExpression Id. */
  int MENU = 15;
  /** RegularExpression Id. */
  int PROPERTY = 16;
  /** RegularExpression Id. */
  int PROPERTYTO = 17;
  /** RegularExpression Id. */
  int PROPERTYVAL = 18;
  /** RegularExpression Id. */
  int MENUSTR = 19;
  /** RegularExpression Id. */
  int STRING = 24;
  /** RegularExpression Id. */
  int SINGLE = 25;
  /** RegularExpression Id. */
  int APOSTROPHE = 26;
  /** RegularExpression Id. */
  int CHAR = 27;
  /** RegularExpression Id. */
  int SETTING_STRING = 32;
  /** RegularExpression Id. */
  int SETTING_SINGLE = 33;
  /** RegularExpression Id. */
  int SETTING_APOSTROPHE = 34;
  /** RegularExpression Id. */
  int SETTING_CHAR = 35;
  /** RegularExpression Id. */
  int ADMINTYPE_STRING = 40;
  /** RegularExpression Id. */
  int ADMINTYPE_SINGLE = 41;
  /** RegularExpression Id. */
  int ADMINTYPE_APOSTROPHE = 42;
  /** RegularExpression Id. */
  int ADMINTYPE_CHAR = 43;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_EXPECTED = 1;
  /** Lexical state. */
  int SETTING_EXPECTED = 2;
  /** Lexical state. */
  int ADMINREF_EXPECTED = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"description\"",
    "\"hidden\"",
    "\"!hidden\"",
    "\"treemenu\"",
    "\"!treemenu\"",
    "\"alt\"",
    "\"href\"",
    "\"label\"",
    "<SETTING>",
    "<COMMAND>",
    "<MENU>",
    "\"property\"",
    "\"to\"",
    "\"value\"",
    "\"menu\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<STRING>",
    "<SINGLE>",
    "\"\\\"\"",
    "<CHAR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SETTING_STRING>",
    "<SETTING_SINGLE>",
    "\"\\\"\"",
    "<SETTING_CHAR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<ADMINTYPE_STRING>",
    "<ADMINTYPE_SINGLE>",
    "\"\\\"\"",
    "<ADMINTYPE_CHAR>",
  };

}
