/* BusObjectParser.java */
/* Generated By:JavaCC: Do not edit this line. BusObjectParser.java */
package org.mxupdate.update;

import java.lang.reflect.InvocationTargetException;
import java.util.Arrays;

import org.mxupdate.mapping.TypeDef_mxJPO;
import org.mxupdate.update.util.AbstractParser_mxJPO;
import org.mxupdate.update.util.AbstractParser_mxJPO.ParseException;
import org.mxupdate.update.util.AbstractParser_mxJPO.SimpleCharStream;
import org.mxupdate.update.util.AbstractParser_mxJPO.Token;
import org.mxupdate.update.util.AbstractParser_mxJPO.TokenMgrError;
import org.mxupdate.update.BusObject_mxJPO.Connection;
import org.mxupdate.update.util.ParameterCache_mxJPO;


/**
 * Parses the update format for {@link BusObject_mxJPO}.
 */
@SuppressWarnings("unused")
class BusObjectParser_mxJPO
    extends AbstractParser_mxJPO<BusObject_mxJPO> implements BusObjectParserConstants_mxJPO {

/**************************************************************************** */

/**
 * Parses one complete command definition.
 *
 * @param _command  target command to update with parsed values
 */
  final public void parse(BusObject_mxJPO _busObject) throws ParseException, SecurityException, IllegalArgumentException, NoSuchMethodException, InstantiationException, IllegalAccessException, InvocationTargetException {Token tmp;
    Connection connection;
    String attrName;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TYPE:
      case DESCRIPTION:
      case CURRENT:
      case ATTRIBUTE:
      case CONNECTION:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TYPE:{
        jj_consume_token(TYPE);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case STRING:{
          tmp = jj_consume_token(STRING);
this.setValue(_busObject, "busType", this.getString(tmp.image));
          break;
          }
        case SINGLE:{
          tmp = jj_consume_token(SINGLE);
this.setValue(_busObject, "busType", this.getSingle(tmp.image));
          break;
          }
        default:
          jj_la1[1] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      case DESCRIPTION:{
        jj_consume_token(DESCRIPTION);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case MULTILINESTRING:{
          tmp = jj_consume_token(MULTILINESTRING);
this.setValue(_busObject, "description", this.getString(tmp.image));
          break;
          }
        case MULTILINESINGLE:{
          tmp = jj_consume_token(MULTILINESINGLE);
this.setValue(_busObject, "description", this.getSingle(tmp.image));
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      case CURRENT:{
        jj_consume_token(CURRENT);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case STRING:{
          tmp = jj_consume_token(STRING);
this.setValue(_busObject, "busCurrent", this.getString(tmp.image));
          break;
          }
        case SINGLE:{
          tmp = jj_consume_token(SINGLE);
this.setValue(_busObject, "busCurrent", this.getSingle(tmp.image));
          break;
          }
        default:
          jj_la1[3] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      case ATTRIBUTE:{
        jj_consume_token(ATTRIBUTE);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ATTRIBUTE_STRING:{
          tmp = jj_consume_token(ATTRIBUTE_STRING);
attrName = this.getString(tmp.image);
          break;
          }
        case ATTRIBUTE_SINGLE:{
          tmp = jj_consume_token(ATTRIBUTE_SINGLE);
attrName = this.getSingle(tmp.image);
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case MULTILINESTRING:{
          tmp = jj_consume_token(MULTILINESTRING);
this.putValue(_busObject, "attrValues", attrName, this.getString(tmp.image));
          break;
          }
        case MULTILINESINGLE:{
          tmp = jj_consume_token(MULTILINESINGLE);
this.putValue(_busObject, "attrValues", attrName, this.getSingle(tmp.image));
          break;
          }
        default:
          jj_la1[5] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      case CONNECTION:{
        jj_consume_token(CONNECTION);
connection = new Connection();this.appendValue(_busObject, "connections", connection);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case STRING:{
          tmp = jj_consume_token(STRING);
this.setValue(connection, "relName", this.getString(tmp.image));
          break;
          }
        case SINGLE:{
          tmp = jj_consume_token(SINGLE);
this.setValue(connection, "relName", this.getSingle(tmp.image));
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case CONNECTIONFROM:{
          jj_consume_token(CONNECTIONFROM);
this.setValue(connection, "direction", "from");
          break;
          }
        case CONNECTIONTO:{
          jj_consume_token(CONNECTIONTO);
this.setValue(connection, "direction", "to");
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(CONNECTION_OPEN);
        label_2:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case CONNECTION_TYPE:
          case CONNECTION_NAME:
          case CONNECTION_REVISION:
          case CONNECTION_ATTRIBUTE:{
            ;
            break;
            }
          default:
            jj_la1[8] = jj_gen;
            break label_2;
          }
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case CONNECTION_TYPE:{
            jj_consume_token(CONNECTION_TYPE);
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case CONNECTION_STRING:{
              tmp = jj_consume_token(CONNECTION_STRING);
this.setValue(connection, "type",           this.getString(tmp.image));
              break;
              }
            case CONNECTION_SINGLE:{
              tmp = jj_consume_token(CONNECTION_SINGLE);
this.setValue(connection, "type",           this.getSingle(tmp.image));
              break;
              }
            default:
              jj_la1[9] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
            break;
            }
          case CONNECTION_NAME:{
            jj_consume_token(CONNECTION_NAME);
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case CONNECTION_STRING:{
              tmp = jj_consume_token(CONNECTION_STRING);
this.setValue(connection, "name",           this.getString(tmp.image));
              break;
              }
            case CONNECTION_SINGLE:{
              tmp = jj_consume_token(CONNECTION_SINGLE);
this.setValue(connection, "name",           this.getSingle(tmp.image));
              break;
              }
            default:
              jj_la1[10] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
            break;
            }
          case CONNECTION_REVISION:{
            jj_consume_token(CONNECTION_REVISION);
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case CONNECTION_STRING:{
              tmp = jj_consume_token(CONNECTION_STRING);
this.setValue(connection, "revision",       this.getString(tmp.image));
              break;
              }
            case CONNECTION_SINGLE:{
              tmp = jj_consume_token(CONNECTION_SINGLE);
this.setValue(connection, "revision",       this.getSingle(tmp.image));
              break;
              }
            default:
              jj_la1[11] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
            break;
            }
          case CONNECTION_ATTRIBUTE:{
            jj_consume_token(CONNECTION_ATTRIBUTE);
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case CONNECTION_ATTRIBUTE_STRING:{
              tmp = jj_consume_token(CONNECTION_ATTRIBUTE_STRING);
attrName = this.getString(tmp.image);
              break;
              }
            case CONNECTION_ATTRIBUTE_SINGLE:{
              tmp = jj_consume_token(CONNECTION_ATTRIBUTE_SINGLE);
attrName = this.getSingle(tmp.image);
              break;
              }
            default:
              jj_la1[12] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case CONNECTION_MULTILINESTRING:{
              tmp = jj_consume_token(CONNECTION_MULTILINESTRING);
this.putValue(_busObject, "attrValues", attrName, this.getString(tmp.image));
              break;
              }
            case CONNECTION_MULTILINESINGLE:{
              tmp = jj_consume_token(CONNECTION_MULTILINESINGLE);
this.putValue(_busObject, "attrValues", attrName, this.getSingle(tmp.image));
              break;
              }
            default:
              jj_la1[13] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
            break;
            }
          default:
            jj_la1[14] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
        jj_consume_token(CONNECTION_CLOSE);
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  /** Generated Token Manager. */
  public BusObjectParserTokenManager_mxJPO token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[16];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x81e0,0x600,0x1800,0x600,0x6000,0x1800,0x600,0x30000,0xf00000,0x3000000,0x3000000,0x3000000,0xc000000,0x30000000,0xf00000,0x81e0,};
   }

  /** Constructor with InputStream. */
  public BusObjectParser_mxJPO(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public BusObjectParser_mxJPO(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new BusObjectParserTokenManager_mxJPO(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public BusObjectParser_mxJPO(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new BusObjectParserTokenManager_mxJPO(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
      jj_input_stream = new SimpleCharStream(stream, 1, 1);
   } else {
      jj_input_stream.ReInit(stream, 1, 1);
   }
   if (token_source == null) {
      token_source = new BusObjectParserTokenManager_mxJPO(jj_input_stream);
   }

    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public BusObjectParser_mxJPO(BusObjectParserTokenManager_mxJPO tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(BusObjectParserTokenManager_mxJPO tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[30];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 16; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 30; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
