/* Generated By:JavaCC: Do not edit this line. BusObjectParserConstants.java */
package org.mxupdate.update;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface BusObjectParserConstants_mxJPO {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TYPE = 5;
  /** RegularExpression Id. */
  int DESCRIPTION = 6;
  /** RegularExpression Id. */
  int CURRENT = 7;
  /** RegularExpression Id. */
  int ATTRIBUTE = 8;
  /** RegularExpression Id. */
  int STRING = 9;
  /** RegularExpression Id. */
  int SINGLE = 10;
  /** RegularExpression Id. */
  int MULTILINESTRING = 11;
  /** RegularExpression Id. */
  int MULTILINESINGLE = 12;
  /** RegularExpression Id. */
  int ATTRIBUTE_STRING = 13;
  /** RegularExpression Id. */
  int ATTRIBUTE_SINGLE = 14;
  /** RegularExpression Id. */
  int CONNECTION = 15;
  /** RegularExpression Id. */
  int CONNECTIONTO = 16;
  /** RegularExpression Id. */
  int CONNECTIONFROM = 17;
  /** RegularExpression Id. */
  int CONNECTION_OPEN = 18;
  /** RegularExpression Id. */
  int CONNECTION_CLOSE = 19;
  /** RegularExpression Id. */
  int CONNECTION_TYPE = 20;
  /** RegularExpression Id. */
  int CONNECTION_NAME = 21;
  /** RegularExpression Id. */
  int CONNECTION_REVISION = 22;
  /** RegularExpression Id. */
  int CONNECTION_ATTRIBUTE = 23;
  /** RegularExpression Id. */
  int CONNECTION_STRING = 24;
  /** RegularExpression Id. */
  int CONNECTION_SINGLE = 25;
  /** RegularExpression Id. */
  int CONNECTION_ATTRIBUTE_STRING = 26;
  /** RegularExpression Id. */
  int CONNECTION_ATTRIBUTE_SINGLE = 27;
  /** RegularExpression Id. */
  int CONNECTION_MULTILINESTRING = 28;
  /** RegularExpression Id. */
  int CONNECTION_MULTILINESINGLE = 29;

  /** Lexical state. */
  int CONNECTION_MULTILINESTRING_EXPECTED = 0;
  /** Lexical state. */
  int CONNECTION_ATTRIBUTE_EXPECTED = 1;
  /** Lexical state. */
  int CONNECTION_STRING_EXPECTED = 2;
  /** Lexical state. */
  int CONNECTION_EXPECTED = 3;
  /** Lexical state. */
  int CONNECTION_OPENEXPECTED = 4;
  /** Lexical state. */
  int ATTRIBUTE_EXPECTED = 5;
  /** Lexical state. */
  int MULTILINESTRING_EXPECTED = 6;
  /** Lexical state. */
  int STRING_EXPECTED = 7;
  /** Lexical state. */
  int DEFAULT = 8;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 4>",
    "\"type\"",
    "\"description\"",
    "\"current\"",
    "\"attribute\"",
    "<STRING>",
    "<SINGLE>",
    "<MULTILINESTRING>",
    "<MULTILINESINGLE>",
    "<ATTRIBUTE_STRING>",
    "<ATTRIBUTE_SINGLE>",
    "\"connection\"",
    "\"to\"",
    "\"from\"",
    "\"{\"",
    "\"}\"",
    "\"type\"",
    "\"name\"",
    "\"revision\"",
    "\"attribute\"",
    "<CONNECTION_STRING>",
    "<CONNECTION_SINGLE>",
    "<CONNECTION_ATTRIBUTE_STRING>",
    "<CONNECTION_ATTRIBUTE_SINGLE>",
    "<CONNECTION_MULTILINESTRING>",
    "<CONNECTION_MULTILINESINGLE>",
  };

}
