/* Generated By:JavaCC: Do not edit this line. ChannelDefParserConstants.java */
package org.mxupdate.update.userinterface.channel;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ChannelDefParserConstants_mxJPO {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DESCRIPTION = 5;
  /** RegularExpression Id. */
  int HIDDEN_TRUE = 6;
  /** RegularExpression Id. */
  int HIDDEN_FALSE = 7;
  /** RegularExpression Id. */
  int LABEL = 8;
  /** RegularExpression Id. */
  int ALT = 9;
  /** RegularExpression Id. */
  int HREF = 10;
  /** RegularExpression Id. */
  int HEIGHT = 11;
  /** RegularExpression Id. */
  int SETTING = 12;
  /** RegularExpression Id. */
  int COMMAND = 13;
  /** RegularExpression Id. */
  int PROPERTY = 14;
  /** RegularExpression Id. */
  int PROPERTYTO = 15;
  /** RegularExpression Id. */
  int PROPERTYVAL = 16;
  /** RegularExpression Id. */
  int STRING = 21;
  /** RegularExpression Id. */
  int SINGLE = 22;
  /** RegularExpression Id. */
  int APOSTROPHE = 23;
  /** RegularExpression Id. */
  int CHAR = 24;
  /** RegularExpression Id. */
  int INTEGER = 29;
  /** RegularExpression Id. */
  int SETTING_STRING = 34;
  /** RegularExpression Id. */
  int SETTING_SINGLE = 35;
  /** RegularExpression Id. */
  int SETTING_APOSTROPHE = 36;
  /** RegularExpression Id. */
  int SETTING_CHAR = 37;
  /** RegularExpression Id. */
  int ADMINTYPE_STRING = 42;
  /** RegularExpression Id. */
  int ADMINTYPE_SINGLE = 43;
  /** RegularExpression Id. */
  int ADMINTYPE_APOSTROPHE = 44;
  /** RegularExpression Id. */
  int ADMINTYPE_CHAR = 45;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_EXPECTED = 1;
  /** Lexical state. */
  int INTEGER_EXPECTED = 2;
  /** Lexical state. */
  int SETTING_EXPECTED = 3;
  /** Lexical state. */
  int ADMINREF_EXPECTED = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"description\"",
    "\"hidden\"",
    "\"!hidden\"",
    "\"label\"",
    "\"alt\"",
    "\"href\"",
    "\"height\"",
    "<SETTING>",
    "<COMMAND>",
    "\"property\"",
    "\"to\"",
    "\"value\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<STRING>",
    "<SINGLE>",
    "\"\\\"\"",
    "<CHAR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<INTEGER>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SETTING_STRING>",
    "<SETTING_SINGLE>",
    "\"\\\"\"",
    "<SETTING_CHAR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<ADMINTYPE_STRING>",
    "<ADMINTYPE_SINGLE>",
    "\"\\\"\"",
    "<ADMINTYPE_CHAR>",
  };

}
