/* Generated By:JavaCC: Do not edit this line. PolicyDefParserConstants.java */
package org.mxupdate.update.datamodel.policy;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface PolicyDefParserConstants_mxJPO {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DESCRIPTION = 5;
  /** RegularExpression Id. */
  int TYPE = 6;
  /** RegularExpression Id. */
  int FORMAT = 7;
  /** RegularExpression Id. */
  int STORE = 8;
  /** RegularExpression Id. */
  int DEFAULTFORMAT = 9;
  /** RegularExpression Id. */
  int ENFORCE = 10;
  /** RegularExpression Id. */
  int DELIMITER = 11;
  /** RegularExpression Id. */
  int SEQUENCE = 12;
  /** RegularExpression Id. */
  int MINORSEQUENCE = 13;
  /** RegularExpression Id. */
  int MAJORSEQUENCE = 14;
  /** RegularExpression Id. */
  int HIDDEN = 15;
  /** RegularExpression Id. */
  int STATE = 16;
  /** RegularExpression Id. */
  int ALLSTATE = 17;
  /** RegularExpression Id. */
  int REGISTEREDNAME = 18;
  /** RegularExpression Id. */
  int REVISION = 19;
  /** RegularExpression Id. */
  int MINORREVISION = 20;
  /** RegularExpression Id. */
  int MAJORREVISION = 21;
  /** RegularExpression Id. */
  int VERSION = 22;
  /** RegularExpression Id. */
  int PROMOTE = 23;
  /** RegularExpression Id. */
  int CHECKOUTHISTORY = 24;
  /** RegularExpression Id. */
  int PUBLISHED = 25;
  /** RegularExpression Id. */
  int REVOKE = 26;
  /** RegularExpression Id. */
  int LOGIN = 27;
  /** RegularExpression Id. */
  int OWNER = 28;
  /** RegularExpression Id. */
  int PUBLIC = 29;
  /** RegularExpression Id. */
  int USER = 30;
  /** RegularExpression Id. */
  int KEY = 31;
  /** RegularExpression Id. */
  int FILTER = 32;
  /** RegularExpression Id. */
  int LOCALFILTER = 33;
  /** RegularExpression Id. */
  int ACTION = 34;
  /** RegularExpression Id. */
  int CHECK = 35;
  /** RegularExpression Id. */
  int OVERRIDE = 36;
  /** RegularExpression Id. */
  int INPUT = 37;
  /** RegularExpression Id. */
  int TRIGGER = 38;
  /** RegularExpression Id. */
  int APPROVE = 39;
  /** RegularExpression Id. */
  int IGNORE = 40;
  /** RegularExpression Id. */
  int REJECT = 41;
  /** RegularExpression Id. */
  int BRANCH = 42;
  /** RegularExpression Id. */
  int SIGNATURE = 43;
  /** RegularExpression Id. */
  int ROUTE = 44;
  /** RegularExpression Id. */
  int ACCESS = 45;
  /** RegularExpression Id. */
  int ORGANIZATION_ANY = 46;
  /** RegularExpression Id. */
  int ORGANIZATION_SINGLE = 47;
  /** RegularExpression Id. */
  int ORGANIZATION_ANCESTOR = 48;
  /** RegularExpression Id. */
  int ORGANIZATION_DESCENDANT = 49;
  /** RegularExpression Id. */
  int ORGANIZATION_RELATED = 50;
  /** RegularExpression Id. */
  int PROJECT_ANY = 51;
  /** RegularExpression Id. */
  int PROJECT_SINGLE = 52;
  /** RegularExpression Id. */
  int PROJECT_ANCESTOR = 53;
  /** RegularExpression Id. */
  int PROJECT_DESCENDANT = 54;
  /** RegularExpression Id. */
  int PROJECT_RELATED = 55;
  /** RegularExpression Id. */
  int OWNER_ANY = 56;
  /** RegularExpression Id. */
  int OWNER_CONTEXT = 57;
  /** RegularExpression Id. */
  int RESERVE_ANY = 58;
  /** RegularExpression Id. */
  int RESERVE_CONTEXT = 59;
  /** RegularExpression Id. */
  int RESERVE_NO = 60;
  /** RegularExpression Id. */
  int RESERVE_INCLUSIVE = 61;
  /** RegularExpression Id. */
  int MATURITY_ANY = 62;
  /** RegularExpression Id. */
  int MATURITY_NO = 63;
  /** RegularExpression Id. */
  int MATURITY_PUBLIC = 64;
  /** RegularExpression Id. */
  int MATURITY_PROTECTED = 65;
  /** RegularExpression Id. */
  int MATURITY_PRIVATE = 66;
  /** RegularExpression Id. */
  int MATURITY_NOTPRIVATE = 67;
  /** RegularExpression Id. */
  int MATURITY_PPP = 68;
  /** RegularExpression Id. */
  int CATEGORY_ANY = 69;
  /** RegularExpression Id. */
  int CATEGORY_OEM = 70;
  /** RegularExpression Id. */
  int CATEGORY_GOLDPARTNER = 71;
  /** RegularExpression Id. */
  int CATEGORY_PARTNER = 72;
  /** RegularExpression Id. */
  int CATEGORY_SUPPLIER = 73;
  /** RegularExpression Id. */
  int CATEGORY_CUSTOMER = 74;
  /** RegularExpression Id. */
  int CATEGORY_CONTRACTOR = 75;
  /** RegularExpression Id. */
  int BOOLEAN_TRUE = 80;
  /** RegularExpression Id. */
  int BOOLEAN_FALSE = 81;
  /** RegularExpression Id. */
  int BOOLEAN_TRUESTR = 82;
  /** RegularExpression Id. */
  int BOOLEAN_FALSESTR = 83;
  /** RegularExpression Id. */
  int DELIMITER_CHAR = 88;
  /** RegularExpression Id. */
  int DELIMITER_CHARSTR = 89;
  /** RegularExpression Id. */
  int LS_CURLY_BRACKET_OPEN = 94;
  /** RegularExpression Id. */
  int LS_CURLY_BRACKET_CLOSE = 95;
  /** RegularExpression Id. */
  int LS_STRING = 96;
  /** RegularExpression Id. */
  int LS_SINGLE_STRING = 97;
  /** RegularExpression Id. */
  int LS_APOSTROPHE = 98;
  /** RegularExpression Id. */
  int LS_CHAR = 99;
  /** RegularExpression Id. */
  int SL_STRING = 104;
  /** RegularExpression Id. */
  int SL_SINGLE_STRING = 105;
  /** RegularExpression Id. */
  int SL_APOSTROPHE = 106;
  /** RegularExpression Id. */
  int SL_CHAR = 107;
  /** RegularExpression Id. */
  int S_STRING = 112;
  /** RegularExpression Id. */
  int S_SINGLE_STRING = 113;
  /** RegularExpression Id. */
  int S_APOSTROPHE = 114;
  /** RegularExpression Id. */
  int S_CHAR = 115;
  /** RegularExpression Id. */
  int LALL_CURLY_BRACKET_OPEN = 120;
  /** RegularExpression Id. */
  int LALL_ALL = 121;
  /** RegularExpression Id. */
  int L_CURLY_BRACKET_OPEN = 126;
  /** RegularExpression Id. */
  int L_CURLY_BRACKET_CLOSE = 131;
  /** RegularExpression Id. */
  int L_STRING = 132;
  /** RegularExpression Id. */
  int L_SINGLE_STRING = 133;
  /** RegularExpression Id. */
  int L_APOSTROPHE = 134;
  /** RegularExpression Id. */
  int L_CHAR = 135;
  /** RegularExpression Id. */
  int L2_CURLY_BRACKET_OPEN = 136;
  /** RegularExpression Id. */
  int L3_BRACE_STRING = 137;
  /** RegularExpression Id. */
  int L3_CHAR = 138;
  /** RegularExpression Id. */
  int L4_CURLY_BRACKET_CLOSE = 139;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int B_EXPECTED = 1;
  /** Lexical state. */
  int D_EXPECTED = 2;
  /** Lexical state. */
  int LS_EXPECTED = 3;
  /** Lexical state. */
  int SL_EXPECTED = 4;
  /** Lexical state. */
  int S_EXPECTED = 5;
  /** Lexical state. */
  int LALL_EXPECTED = 6;
  /** Lexical state. */
  int L_EXPECTED = 7;
  /** Lexical state. */
  int L2_EXPECTED = 8;
  /** Lexical state. */
  int L3_EXPECTED = 9;
  /** Lexical state. */
  int L4_EXPECTED = 10;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"description\"",
    "\"type\"",
    "\"format\"",
    "\"store\"",
    "\"defaultformat\"",
    "\"enforce\"",
    "\"delimiter\"",
    "\"sequence\"",
    "\"minorsequence\"",
    "\"majorsequence\"",
    "\"hidden\"",
    "\"state\"",
    "\"allstate\"",
    "\"registeredName\"",
    "\"revision\"",
    "\"minorrevision\"",
    "\"majorrevision\"",
    "\"version\"",
    "\"promote\"",
    "\"checkouthistory\"",
    "\"published\"",
    "\"revoke\"",
    "\"login\"",
    "\"owner\"",
    "\"public\"",
    "\"user\"",
    "\"key\"",
    "\"filter\"",
    "\"localfilter\"",
    "\"action\"",
    "\"check\"",
    "\"override\"",
    "\"input\"",
    "\"trigger\"",
    "\"approve\"",
    "\"ignore\"",
    "\"reject\"",
    "\"branch\"",
    "\"signature\"",
    "\"route\"",
    "<ACCESS>",
    "<ORGANIZATION_ANY>",
    "<ORGANIZATION_SINGLE>",
    "<ORGANIZATION_ANCESTOR>",
    "<ORGANIZATION_DESCENDANT>",
    "<ORGANIZATION_RELATED>",
    "<PROJECT_ANY>",
    "<PROJECT_SINGLE>",
    "<PROJECT_ANCESTOR>",
    "<PROJECT_DESCENDANT>",
    "<PROJECT_RELATED>",
    "<OWNER_ANY>",
    "<OWNER_CONTEXT>",
    "<RESERVE_ANY>",
    "<RESERVE_CONTEXT>",
    "<RESERVE_NO>",
    "<RESERVE_INCLUSIVE>",
    "<MATURITY_ANY>",
    "<MATURITY_NO>",
    "<MATURITY_PUBLIC>",
    "<MATURITY_PROTECTED>",
    "<MATURITY_PRIVATE>",
    "<MATURITY_NOTPRIVATE>",
    "<MATURITY_PPP>",
    "<CATEGORY_ANY>",
    "<CATEGORY_OEM>",
    "<CATEGORY_GOLDPARTNER>",
    "<CATEGORY_PARTNER>",
    "<CATEGORY_SUPPLIER>",
    "<CATEGORY_CUSTOMER>",
    "<CATEGORY_CONTRACTOR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<BOOLEAN_TRUE>",
    "<BOOLEAN_FALSE>",
    "<BOOLEAN_TRUESTR>",
    "<BOOLEAN_FALSESTR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<DELIMITER_CHAR>",
    "<DELIMITER_CHARSTR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
    "<LS_STRING>",
    "<LS_SINGLE_STRING>",
    "\"\\\"\"",
    "<LS_CHAR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SL_STRING>",
    "<SL_SINGLE_STRING>",
    "\"\\\"\"",
    "<SL_CHAR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<S_STRING>",
    "<S_SINGLE_STRING>",
    "\"\\\"\"",
    "<S_CHAR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"all\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"}\"",
    "<L_STRING>",
    "<L_SINGLE_STRING>",
    "\"\\\"\"",
    "<L_CHAR>",
    "\"{\"",
    "<L3_BRACE_STRING>",
    "<L3_CHAR>",
    "\"}\"",
    "\"{\"",
    "\"}\"",
  };

}
